hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_multi_crossing_medium_589769021
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -8.9
      2:
        x: -8.63
        y: -8.6
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -8.63
        y: -8.15
      6:
        x: -8.63
        y: -7.4
      7:
        x: -8.63
        y: -7.1
      8:
        x: -7.65
        y: -5.4
      9:
        x: -3.73
        y: -7.1
      10:
        x: -3.73
        y: -7.4
      11:
        x: -3.73
        y: -8.15
      12:
        x: -5.0
        y: -8.15
      13:
        x: -3.73
        y: -8.15
      14:
        x: -3.73
        y: -8.6
      15:
        x: -3.73
        y: -8.9
      16:
        x: -2.75
        y: -10.6
      17:
        x: 1.17
        y: -8.9
      18:
        x: 1.17
        y: -8.6
      19:
        x: 1.17
        y: -8.15
      20:
        x: 0.0
        y: -7.85
      21:
        x: 1.17
        y: -8.15
      22:
        x: 1.17
        y: -7.4
      23:
        x: 1.17
        y: -7.1
      24:
        x: 2.15
        y: -5.4
      25:
        x: -3.73
        y: -8.9
      26:
        x: -3.73
        y: -8.6
      27:
        x: -3.73
        y: -8.15
      28:
        x: -5.0
        y: -8.15
      29:
        x: -2.0
        y: -8.18
      30:
        x: 0.0
        y: -7.85
      31:
        x: 2.6
        y: -8.15
      32:
        x: 5.0
        y: -8.15
      33:
        x: 10.0
        y: -8.15
      34:
        x: 10.97
        y: -8.15
      35:
        x: 10.97
        y: -8.6
      36:
        x: 10.97
        y: -8.9
      37:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.6686
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 1.3889
    event_agent_2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.5641
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      start_delay: 8.8641
    event_agent_3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.9761
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      start_delay: 21.3672
    background_agent_1:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9617
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      start_delay: 2.154
