hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_opposing_group_high_1032642966
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -14.0
        y: -8.15
      2:
        x: -14.0
        y: -8.15
      3:
        x: -14.0
        y: -8.15
      4:
        x: 14.1
        y: 6.01
      5:
        x: 14.4
        y: 6.01
      6:
        x: 15.0
        y: 6.01
      7:
        x: 15.0
        y: 8.0
      8:
        x: 15.0
        y: 9.8
      9:
        x: 15.0
        y: 10.65
      10:
        x: 15.0
        y: 10.8733
      11:
        x: 15.6
        y: 10.8733
      12:
        x: 15.9
        y: 10.8733
      13:
        x: 17.6
        y: 11.7667
      14:
        x: -8.63
        y: -7.1
      15:
        x: -8.63
        y: -7.4
      16:
        x: -8.63
        y: -8.15
      17:
        x: -10.0
        y: -7.85
      18:
        x: -8.63
        y: -8.15
      19:
        x: -8.63
        y: -8.6
      20:
        x: -8.63
        y: -8.9
      21:
        x: -7.65
        y: -10.6
      22:
        x: 6.07
        y: -8.9
      23:
        x: 6.07
        y: -8.6
      24:
        x: 6.07
        y: -8.15
      25:
        x: 5.0
        y: -8.15
      26:
        x: 10.0
        y: -8.15
      27:
        x: 10.97
        y: -8.15
      28:
        x: 10.97
        y: -8.6
      29:
        x: 10.97
        y: -8.9
      30:
        x: 11.95
        y: -10.6
      31:
        x: 15.9
        y: 10.8733
      32:
        x: 15.6
        y: 10.8733
      33:
        x: 15.0
        y: 10.8733
      34:
        x: 15.0
        y: 10.65
      35:
        x: 15.0
        y: 9.8
      36:
        x: 15.0
        y: 8.0
      37:
        x: 15.0
        y: 3.5
      38:
        x: 15.0
        y: 2.55
      39:
        x: 15.0
        y: 0.0
      40:
        x: 7.0
        y: 0.0
      41:
        x: 7.0
        y: -2.0
      42:
        x: 7.0
        y: -4.0
      43:
        x: 15.0
        y: -4.0
      44:
        x: 15.0
        y: -8.15
      45:
        x: 10.0
        y: -8.15
      46:
        x: 5.0
        y: -8.15
      47:
        x: 2.6
        y: -8.15
      48:
        x: 0.0
        y: -7.85
      49:
        x: 1.17
        y: -8.15
      50:
        x: 1.17
        y: -8.6
      51:
        x: 1.17
        y: -8.9
      52:
        x: 2.15
        y: -10.6
      53:
        x: 15.9
        y: 6.4067
      54:
        x: 15.6
        y: 6.4067
      55:
        x: 15.0
        y: 6.4067
      56:
        x: 15.0
        y: 8.0
      57:
        x: 15.0
        y: 3.5
      58:
        x: 15.0
        y: 2.55
      59:
        x: 15.0
        y: 0.0
      60:
        x: 7.0
        y: 0.0
      61:
        x: 7.0
        y: -2.0
      62:
        x: 7.0
        y: -4.0
      63:
        x: 15.0
        y: -4.0
      64:
        x: 15.0
        y: -8.15
      65:
        x: 10.0
        y: -8.15
      66:
        x: 5.0
        y: -8.15
      67:
        x: 2.6
        y: -8.15
      68:
        x: 0.0
        y: -7.85
      69:
        x: -2.0
        y: -8.18
      70:
        x: -5.0
        y: -8.15
      71:
        x: -10.0
        y: -7.85
      72:
        x: -8.63
        y: -8.15
      73:
        x: -8.63
        y: -7.4
      74:
        x: -8.63
        y: -7.1
      75:
        x: -7.65
        y: -5.4
      76:
        x: 1.17
        y: -8.9
      77:
        x: 1.17
        y: -8.6
      78:
        x: 1.17
        y: -8.15
      79:
        x: 0.0
        y: -7.85
      80:
        x: -2.0
        y: -8.18
      81:
        x: -5.0
        y: -8.15
      82:
        x: -10.0
        y: -7.85
      83:
        x: -8.63
        y: -8.15
      84:
        x: -8.63
        y: -8.6
      85:
        x: -8.63
        y: -8.9
      86:
        x: -7.65
        y: -10.6
      87:
        x: 10.97
        y: -8.9
      88:
        x: 10.97
        y: -8.6
      89:
        x: 10.97
        y: -8.15
      90:
        x: 10.0
        y: -8.15
      91:
        x: 15.0
        y: -8.15
      92:
        x: 15.0
        y: -4.0
      93:
        x: 7.0
        y: -4.0
      94:
        x: 7.0
        y: -2.0
      95:
        x: 7.0
        y: 0.0
      96:
        x: 15.0
        y: 0.0
      97:
        x: 15.0
        y: 2.55
      98:
        x: 15.0
        y: 3.5
      99:
        x: 15.0
        y: 8.0
      100:
        x: 15.0
        y: 9.8
      101:
        x: 15.0
        y: 10.65
      102:
        x: 15.0
        y: 10.8733
      103:
        x: 15.6
        y: 10.8733
      104:
        x: 15.9
        y: 10.8733
      105:
        x: 17.6
        y: 11.7667
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.9346
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -9.99845
        y: -7.87062
        z: 0.0
        h: -3.066733
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      start_delay: 0.2917
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.9346
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -10.59178
        y: -7.90561
        z: 0.0
        h: -3.066733
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 2
      start_delay: 0.2917
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.9346
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -11.18436
        y: -7.95065
        z: 0.0
        h: -3.066733
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      start_delay: 0.2917
    background_agent_1:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.6433
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      start_delay: 1.2508
    background_agent_2:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.8533
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      start_delay: 1.7237
    background_agent_3:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.8503
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 0.5799
    background_agent_4:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.9638
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      start_delay: 4.6451
    background_agent_5:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.9566
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      start_delay: 0.6003
    background_agent_6:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.868
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      start_delay: 1.977
    background_agent_7:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.9132
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      start_delay: 4.5798
