hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_multi_crossing_high_76852548
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -7.1
      2:
        x: -8.63
        y: -7.4
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -8.63
        y: -8.15
      6:
        x: -8.63
        y: -8.6
      7:
        x: -8.63
        y: -8.9
      8:
        x: -7.65
        y: -10.6
      9:
        x: -3.73
        y: -8.9
      10:
        x: -3.73
        y: -8.6
      11:
        x: -3.73
        y: -8.15
      12:
        x: -5.0
        y: -8.15
      13:
        x: -3.73
        y: -8.15
      14:
        x: -3.73
        y: -7.4
      15:
        x: -3.73
        y: -7.1
      16:
        x: -2.75
        y: -5.4
      17:
        x: 1.17
        y: -7.1
      18:
        x: 1.17
        y: -7.4
      19:
        x: 1.17
        y: -8.15
      20:
        x: 0.0
        y: -7.85
      21:
        x: 1.17
        y: -8.15
      22:
        x: 1.17
        y: -8.6
      23:
        x: 1.17
        y: -8.9
      24:
        x: 2.15
        y: -10.6
      25:
        x: 15.9
        y: 10.8733
      26:
        x: 15.6
        y: 10.8733
      27:
        x: 15.0
        y: 10.8733
      28:
        x: 15.0
        y: 10.65
      29:
        x: 15.0
        y: 9.8
      30:
        x: 15.0
        y: 8.0
      31:
        x: 15.0
        y: 3.5
      32:
        x: 15.0
        y: 2.55
      33:
        x: 15.0
        y: 0.0
      34:
        x: 7.0
        y: 0.0
      35:
        x: 7.0
        y: -2.0
      36:
        x: 7.0
        y: -4.0
      37:
        x: 15.0
        y: -4.0
      38:
        x: 15.0
        y: -8.15
      39:
        x: 10.0
        y: -8.15
      40:
        x: 5.0
        y: -8.15
      41:
        x: 2.6
        y: -8.15
      42:
        x: 0.0
        y: -7.85
      43:
        x: -2.0
        y: -8.18
      44:
        x: -5.0
        y: -8.15
      45:
        x: -10.0
        y: -7.85
      46:
        x: -14.0
        y: -8.15
      47:
        x: -13.53
        y: -8.15
      48:
        x: -13.53
        y: -8.6
      49:
        x: -13.53
        y: -8.9
      50:
        x: -12.55
        y: -10.6
      51:
        x: 1.17
        y: -8.9
      52:
        x: 1.17
        y: -8.6
      53:
        x: 1.17
        y: -8.15
      54:
        x: 0.0
        y: -7.85
      55:
        x: -2.0
        y: -8.18
      56:
        x: -5.0
        y: -8.15
      57:
        x: -3.73
        y: -8.15
      58:
        x: -3.73
        y: -8.6
      59:
        x: -3.73
        y: -8.9
      60:
        x: -2.75
        y: -10.6
      61:
        x: 10.97
        y: -8.9
      62:
        x: 10.97
        y: -8.6
      63:
        x: 10.97
        y: -8.15
      64:
        x: 10.0
        y: -8.15
      65:
        x: 15.0
        y: -8.15
      66:
        x: 15.0
        y: -4.0
      67:
        x: 7.0
        y: -4.0
      68:
        x: 7.0
        y: -2.0
      69:
        x: 7.0
        y: 0.0
      70:
        x: 15.0
        y: 0.0
      71:
        x: 15.0
        y: 2.55
      72:
        x: 15.0
        y: 1.94
      73:
        x: 15.6
        y: 1.94
      74:
        x: 15.9
        y: 1.94
      75:
        x: 17.6
        y: 2.8333
      76:
        x: 15.9
        y: 1.94
      77:
        x: 15.6
        y: 1.94
      78:
        x: 15.0
        y: 1.94
      79:
        x: 15.0
        y: 2.55
      80:
        x: 15.0
        y: 0.0
      81:
        x: 7.0
        y: 0.0
      82:
        x: 7.0
        y: -2.0
      83:
        x: 7.0
        y: -4.0
      84:
        x: 15.0
        y: -4.0
      85:
        x: 15.0
        y: -8.15
      86:
        x: 10.0
        y: -8.15
      87:
        x: 10.97
        y: -8.15
      88:
        x: 10.97
        y: -8.6
      89:
        x: 10.97
        y: -8.9
      90:
        x: 11.95
        y: -10.6
      91:
        x: 6.07
        y: -8.9
      92:
        x: 6.07
        y: -8.6
      93:
        x: 6.07
        y: -8.15
      94:
        x: 5.0
        y: -8.15
      95:
        x: 2.6
        y: -8.15
      96:
        x: 0.0
        y: -7.85
      97:
        x: -2.0
        y: -8.18
      98:
        x: -5.0
        y: -8.15
      99:
        x: -10.0
        y: -7.85
      100:
        x: -14.0
        y: -8.15
      101:
        x: -13.53
        y: -8.15
      102:
        x: -13.53
        y: -8.6
      103:
        x: -13.53
        y: -8.9
      104:
        x: -12.55
        y: -10.6
      105:
        x: -3.73
        y: -7.1
      106:
        x: -3.73
        y: -7.4
      107:
        x: -3.73
        y: -8.15
      108:
        x: -5.0
        y: -8.15
      109:
        x: -2.0
        y: -8.18
      110:
        x: 0.0
        y: -7.85
      111:
        x: 2.6
        y: -8.15
      112:
        x: 5.0
        y: -8.15
      113:
        x: 10.0
        y: -8.15
      114:
        x: 15.0
        y: -8.15
      115:
        x: 15.0
        y: -4.0
      116:
        x: 7.0
        y: -4.0
      117:
        x: 7.0
        y: -2.0
      118:
        x: 7.0
        y: 0.0
      119:
        x: 15.0
        y: 0.0
      120:
        x: 15.0
        y: 2.55
      121:
        x: 15.0
        y: 1.94
      122:
        x: 15.6
        y: 1.94
      123:
        x: 15.9
        y: 1.94
      124:
        x: 17.6
        y: 2.8333
      125:
        x: -13.53
        y: -7.1
      126:
        x: -13.53
        y: -7.4
      127:
        x: -13.53
        y: -8.15
      128:
        x: -14.0
        y: -8.15
      129:
        x: -10.0
        y: -7.85
      130:
        x: -5.0
        y: -8.15
      131:
        x: -3.73
        y: -8.15
      132:
        x: -3.73
        y: -8.6
      133:
        x: -3.73
        y: -8.9
      134:
        x: -2.75
        y: -10.6
      135:
        x: 15.9
        y: 6.4067
      136:
        x: 15.6
        y: 6.4067
      137:
        x: 15.0
        y: 6.4067
      138:
        x: 15.0
        y: 8.0
      139:
        x: 15.0
        y: 9.8
      140:
        x: 15.0
        y: 10.65
      141:
        x: 15.0
        y: 10.8733
      142:
        x: 15.6
        y: 10.8733
      143:
        x: 15.9
        y: 10.8733
      144:
        x: 17.6
        y: 11.7667
      145:
        x: -8.63
        y: -8.9
      146:
        x: -8.63
        y: -8.6
      147:
        x: -8.63
        y: -8.15
      148:
        x: -10.0
        y: -7.85
      149:
        x: -14.0
        y: -8.15
      150:
        x: -13.53
        y: -8.15
      151:
        x: -13.53
        y: -7.4
      152:
        x: -13.53
        y: -7.1
      153:
        x: -12.55
        y: -5.4
      154:
        x: -13.53
        y: -8.9
      155:
        x: -13.53
        y: -8.6
      156:
        x: -13.53
        y: -8.15
      157:
        x: -14.0
        y: -8.15
      158:
        x: -10.0
        y: -7.85
      159:
        x: -5.0
        y: -8.15
      160:
        x: -2.0
        y: -8.18
      161:
        x: 0.0
        y: -7.85
      162:
        x: 2.6
        y: -8.15
      163:
        x: 5.0
        y: -8.15
      164:
        x: 6.07
        y: -8.15
      165:
        x: 6.07
        y: -8.6
      166:
        x: 6.07
        y: -8.9
      167:
        x: 7.05
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.9552
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 2.3973
    event_agent_2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9484
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      start_delay: 12.0046
    event_agent_3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7442
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      start_delay: 19.5749
    background_agent_1:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7873
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      start_delay: 3.1267
    background_agent_2:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.5925
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      start_delay: 4.0564
    background_agent_3:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7777
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      start_delay: 0.2327
    background_agent_4:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.5655
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      start_delay: 0.4327
    background_agent_5:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.6379
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      start_delay: 0.2216
    background_agent_6:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.8106
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      start_delay: 3.7273
    background_agent_7:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.7179
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      start_delay: 0.2806
    background_agent_8:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.8902
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      start_delay: 3.6151
    background_agent_9:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.6458
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 145
      - 146
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      start_delay: 0.3697
    background_agent_10:
      id: 13
      group_id: -1
      skin: 0
      max_vel: 0.9562
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 154
      - 155
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      - 165
      - 166
      - 167
      start_delay: 1.941
