hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_head_on_low_1401731410
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 5.0
        y: -8.15
      2:
        x: 2.6
        y: -8.15
      3:
        x: 0.0
        y: -7.85
      4:
        x: -2.0
        y: -8.18
      5:
        x: 14.1
        y: 6.01
      6:
        x: 14.4
        y: 6.01
      7:
        x: 15.0
        y: 6.01
      8:
        x: 15.0
        y: 8.0
      9:
        x: 15.0
        y: 3.5
      10:
        x: 15.0
        y: 2.55
      11:
        x: 15.0
        y: 1.94
      12:
        x: 15.6
        y: 1.94
      13:
        x: 15.9
        y: 1.94
      14:
        x: 17.6
        y: 2.8333
      15:
        x: -3.73
        y: -7.1
      16:
        x: -3.73
        y: -7.4
      17:
        x: -3.73
        y: -8.15
      18:
        x: -5.0
        y: -8.15
      19:
        x: -2.0
        y: -8.18
      20:
        x: 0.0
        y: -7.85
      21:
        x: 2.6
        y: -8.15
      22:
        x: 5.0
        y: -8.15
      23:
        x: 10.0
        y: -8.15
      24:
        x: 10.97
        y: -8.15
      25:
        x: 10.97
        y: -8.6
      26:
        x: 10.97
        y: -8.9
      27:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.781
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 10.0
        y: -8.09671
        z: 0.0
        h: 3.141593
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 0.6504
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.74
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      start_delay: 4.4986
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.949
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      start_delay: 2.1603
