hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_robot_overtake_high_656765341
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 9.8
      2:
        x: 15.0
        y: 10.65
      3:
        x: 15.0
        y: 12.3
      4:
        x: 15.0
        y: 13.5
      5:
        x: -13.53
        y: -8.9
      6:
        x: -13.53
        y: -8.6
      7:
        x: -13.53
        y: -8.15
      8:
        x: -14.0
        y: -8.15
      9:
        x: -13.53
        y: -8.15
      10:
        x: -13.53
        y: -7.4
      11:
        x: -13.53
        y: -7.1
      12:
        x: -12.55
        y: -5.4
      13:
        x: 15.9
        y: 6.4067
      14:
        x: 15.6
        y: 6.4067
      15:
        x: 15.0
        y: 6.4067
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 3.5
      18:
        x: 15.0
        y: 2.55
      19:
        x: 15.0
        y: 0.0
      20:
        x: 7.0
        y: 0.0
      21:
        x: 7.0
        y: -2.0
      22:
        x: 7.0
        y: -4.0
      23:
        x: 15.0
        y: -4.0
      24:
        x: 15.0
        y: -8.15
      25:
        x: 10.0
        y: -8.15
      26:
        x: 5.0
        y: -8.15
      27:
        x: 6.07
        y: -8.15
      28:
        x: 6.07
        y: -8.6
      29:
        x: 6.07
        y: -8.9
      30:
        x: 7.05
        y: -10.6
      31:
        x: 14.1
        y: 10.71
      32:
        x: 14.4
        y: 10.71
      33:
        x: 15.0
        y: 10.71
      34:
        x: 15.0
        y: 10.65
      35:
        x: 15.0
        y: 9.8
      36:
        x: 15.0
        y: 8.0
      37:
        x: 15.0
        y: 6.4067
      38:
        x: 15.6
        y: 6.4067
      39:
        x: 15.9
        y: 6.4067
      40:
        x: 17.6
        y: 7.3
      41:
        x: -13.53
        y: -7.1
      42:
        x: -13.53
        y: -7.4
      43:
        x: -13.53
        y: -8.15
      44:
        x: -14.0
        y: -8.15
      45:
        x: -10.0
        y: -7.85
      46:
        x: -5.0
        y: -8.15
      47:
        x: -2.0
        y: -8.18
      48:
        x: 0.0
        y: -7.85
      49:
        x: 2.6
        y: -8.15
      50:
        x: 5.0
        y: -8.15
      51:
        x: 6.07
        y: -8.15
      52:
        x: 6.07
        y: -8.6
      53:
        x: 6.07
        y: -8.9
      54:
        x: 7.05
        y: -10.6
      55:
        x: 15.9
        y: 10.8733
      56:
        x: 15.6
        y: 10.8733
      57:
        x: 15.0
        y: 10.8733
      58:
        x: 15.0
        y: 10.65
      59:
        x: 15.0
        y: 9.8
      60:
        x: 15.0
        y: 8.0
      61:
        x: 15.0
        y: 3.5
      62:
        x: 15.0
        y: 2.55
      63:
        x: 15.0
        y: 0.0
      64:
        x: 7.0
        y: 0.0
      65:
        x: 7.0
        y: -2.0
      66:
        x: 7.0
        y: -4.0
      67:
        x: 15.0
        y: -4.0
      68:
        x: 15.0
        y: -8.15
      69:
        x: 10.0
        y: -8.15
      70:
        x: 5.0
        y: -8.15
      71:
        x: 2.6
        y: -8.15
      72:
        x: 0.0
        y: -7.85
      73:
        x: -2.0
        y: -8.18
      74:
        x: -5.0
        y: -8.15
      75:
        x: -3.73
        y: -8.15
      76:
        x: -3.73
        y: -7.4
      77:
        x: -3.73
        y: -7.1
      78:
        x: -2.75
        y: -5.4
      79:
        x: 1.17
        y: -7.1
      80:
        x: 1.17
        y: -7.4
      81:
        x: 1.17
        y: -8.15
      82:
        x: 0.0
        y: -7.85
      83:
        x: -2.0
        y: -8.18
      84:
        x: -5.0
        y: -8.15
      85:
        x: -10.0
        y: -7.85
      86:
        x: -14.0
        y: -8.15
      87:
        x: -13.53
        y: -8.15
      88:
        x: -13.53
        y: -7.4
      89:
        x: -13.53
        y: -7.1
      90:
        x: -12.55
        y: -5.4
      91:
        x: 10.97
        y: -8.9
      92:
        x: 10.97
        y: -8.6
      93:
        x: 10.97
        y: -8.15
      94:
        x: 10.0
        y: -8.15
      95:
        x: 5.0
        y: -8.15
      96:
        x: 2.6
        y: -8.15
      97:
        x: 0.0
        y: -7.85
      98:
        x: 1.17
        y: -8.15
      99:
        x: 1.17
        y: -8.6
      100:
        x: 1.17
        y: -8.9
      101:
        x: 2.15
        y: -10.6
      102:
        x: -3.73
        y: -8.9
      103:
        x: -3.73
        y: -8.6
      104:
        x: -3.73
        y: -8.15
      105:
        x: -5.0
        y: -8.15
      106:
        x: -10.0
        y: -7.85
      107:
        x: -14.0
        y: -8.15
      108:
        x: -13.53
        y: -8.15
      109:
        x: -13.53
        y: -7.4
      110:
        x: -13.53
        y: -7.1
      111:
        x: -12.55
        y: -5.4
      112:
        x: -3.73
        y: -7.1
      113:
        x: -3.73
        y: -7.4
      114:
        x: -3.73
        y: -8.15
      115:
        x: -5.0
        y: -8.15
      116:
        x: -2.0
        y: -8.18
      117:
        x: 0.0
        y: -7.85
      118:
        x: 2.6
        y: -8.15
      119:
        x: 5.0
        y: -8.15
      120:
        x: 10.0
        y: -8.15
      121:
        x: 15.0
        y: -8.15
      122:
        x: 15.0
        y: -4.0
      123:
        x: 7.0
        y: -4.0
      124:
        x: 7.0
        y: -2.0
      125:
        x: 7.0
        y: 0.0
      126:
        x: 15.0
        y: 0.0
      127:
        x: 15.0
        y: 2.55
      128:
        x: 15.0
        y: 1.94
      129:
        x: 15.6
        y: 1.94
      130:
        x: 15.9
        y: 1.94
      131:
        x: 17.6
        y: 2.8333
      132:
        x: 14.1
        y: 6.01
      133:
        x: 14.4
        y: 6.01
      134:
        x: 15.0
        y: 6.01
      135:
        x: 15.0
        y: 8.0
      136:
        x: 15.0
        y: 3.5
      137:
        x: 15.0
        y: 2.55
      138:
        x: 15.0
        y: 0.0
      139:
        x: 7.0
        y: 0.0
      140:
        x: 7.0
        y: -2.0
      141:
        x: 7.0
        y: -4.0
      142:
        x: 15.0
        y: -4.0
      143:
        x: 15.0
        y: -8.15
      144:
        x: 10.0
        y: -8.15
      145:
        x: 5.0
        y: -8.15
      146:
        x: 2.6
        y: -8.15
      147:
        x: 0.0
        y: -7.85
      148:
        x: -2.0
        y: -8.18
      149:
        x: -5.0
        y: -8.15
      150:
        x: -10.0
        y: -7.85
      151:
        x: -14.0
        y: -8.15
      152:
        x: -13.53
        y: -8.15
      153:
        x: -13.53
        y: -8.6
      154:
        x: -13.53
        y: -8.9
      155:
        x: -12.55
        y: -10.6
      156:
        x: -8.63
        y: -8.9
      157:
        x: -8.63
        y: -8.6
      158:
        x: -8.63
        y: -8.15
      159:
        x: -10.0
        y: -7.85
      160:
        x: -5.0
        y: -8.15
      161:
        x: -2.0
        y: -8.18
      162:
        x: 0.0
        y: -7.85
      163:
        x: 2.6
        y: -8.15
      164:
        x: 5.0
        y: -8.15
      165:
        x: 10.0
        y: -8.15
      166:
        x: 15.0
        y: -8.15
      167:
        x: 15.0
        y: -4.0
      168:
        x: 7.0
        y: -4.0
      169:
        x: 7.0
        y: -2.0
      170:
        x: 7.0
        y: 0.0
      171:
        x: 15.0
        y: 0.0
      172:
        x: 15.0
        y: 2.55
      173:
        x: 15.0
        y: 1.94
      174:
        x: 15.6
        y: 1.94
      175:
        x: 15.9
        y: 1.94
      176:
        x: 17.6
        y: 2.8333
      177:
        x: 15.9
        y: 1.94
      178:
        x: 15.6
        y: 1.94
      179:
        x: 15.0
        y: 1.94
      180:
        x: 15.0
        y: 2.55
      181:
        x: 15.0
        y: 0.0
      182:
        x: 7.0
        y: 0.0
      183:
        x: 7.0
        y: -2.0
      184:
        x: 7.0
        y: -4.0
      185:
        x: 15.0
        y: -4.0
      186:
        x: 15.0
        y: -8.15
      187:
        x: 10.0
        y: -8.15
      188:
        x: 5.0
        y: -8.15
      189:
        x: 2.6
        y: -8.15
      190:
        x: 0.0
        y: -7.85
      191:
        x: 1.17
        y: -8.15
      192:
        x: 1.17
        y: -8.6
      193:
        x: 1.17
        y: -8.9
      194:
        x: 2.15
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    - background_agent_11
    - background_agent_12
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.2649
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.97541
        y: 8.0
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 0.3837
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6203
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      start_delay: 4.8433
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.9382
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 2.984
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.6499
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      start_delay: 0.5363
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.5627
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      start_delay: 1.7127
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.5611
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      start_delay: 3.0824
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8247
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      start_delay: 3.6968
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.6638
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      start_delay: 3.1715
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.7324
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      start_delay: 3.9793
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.8651
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      start_delay: 2.3057
    background_agent_10:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.8692
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      - 146
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      - 154
      - 155
      start_delay: 1.7801
    background_agent_11:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.9745
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      - 165
      - 166
      - 167
      - 168
      - 169
      - 170
      - 171
      - 172
      - 173
      - 174
      - 175
      - 176
      start_delay: 4.2329
    background_agent_12:
      id: 13
      group_id: -1
      skin: 0
      max_vel: 0.7094
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 177
      - 178
      - 179
      - 180
      - 181
      - 182
      - 183
      - 184
      - 185
      - 186
      - 187
      - 188
      - 189
      - 190
      - 191
      - 192
      - 193
      - 194
      start_delay: 1.4336
