hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_crossing_low_916242500
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -7.1
      2:
        x: -8.63
        y: -7.4
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -8.63
        y: -8.15
      6:
        x: -8.63
        y: -8.6
      7:
        x: -8.63
        y: -8.9
      8:
        x: -7.65
        y: -10.6
      9:
        x: -3.73
        y: -8.9
      10:
        x: -3.73
        y: -8.6
      11:
        x: -3.73
        y: -8.15
      12:
        x: -5.0
        y: -8.15
      13:
        x: -2.0
        y: -8.18
      14:
        x: 0.0
        y: -7.85
      15:
        x: 1.17
        y: -8.15
      16:
        x: 1.17
        y: -8.6
      17:
        x: 1.17
        y: -8.9
      18:
        x: 2.15
        y: -10.6
      19:
        x: -3.73
        y: -7.1
      20:
        x: -3.73
        y: -7.4
      21:
        x: -3.73
        y: -8.15
      22:
        x: -5.0
        y: -8.15
      23:
        x: -10.0
        y: -7.85
      24:
        x: -14.0
        y: -8.15
      25:
        x: -13.53
        y: -8.15
      26:
        x: -13.53
        y: -8.6
      27:
        x: -13.53
        y: -8.9
      28:
        x: -12.55
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.827
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 2.1891
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.559
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      start_delay: 4.6663
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.8118
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      start_delay: 2.7655
