hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_head_on_low_42
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 5.0
        y: -8.15
      2:
        x: 2.6
        y: -8.15
      3:
        x: 0.0
        y: -7.85
      4:
        x: -2.0
        y: -8.18
      5:
        x: -5.0
        y: -8.15
      6:
        x: 10.97
        y: -8.9
      7:
        x: 10.97
        y: -8.6
      8:
        x: 10.97
        y: -8.15
      9:
        x: 10.0
        y: -8.15
      10:
        x: 5.0
        y: -8.15
      11:
        x: 2.6
        y: -8.15
      12:
        x: 0.0
        y: -7.85
      13:
        x: 1.17
        y: -8.15
      14:
        x: 1.17
        y: -8.6
      15:
        x: 1.17
        y: -8.9
      16:
        x: 2.15
        y: -10.6
      17:
        x: -8.63
        y: -7.1
      18:
        x: -8.63
        y: -7.4
      19:
        x: -8.63
        y: -8.15
      20:
        x: -10.0
        y: -7.85
      21:
        x: -5.0
        y: -8.15
      22:
        x: -2.0
        y: -8.18
      23:
        x: 0.0
        y: -7.85
      24:
        x: 2.6
        y: -8.15
      25:
        x: 5.0
        y: -8.15
      26:
        x: 10.0
        y: -8.15
      27:
        x: 15.0
        y: -8.15
      28:
        x: 15.0
        y: -4.0
      29:
        x: 7.0
        y: -4.0
      30:
        x: 7.0
        y: -2.0
      31:
        x: 7.0
        y: 0.0
      32:
        x: 15.0
        y: 0.0
      33:
        x: 15.0
        y: 2.55
      34:
        x: 15.0
        y: 3.5
      35:
        x: 15.0
        y: 8.0
      36:
        x: 15.0
        y: 6.01
      37:
        x: 14.4
        y: 6.01
      38:
        x: 14.1
        y: 6.01
      39:
        x: 12.4
        y: 6.95
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.6128
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 10.0
        y: -8.11939
        z: 0.0
        h: 3.141593
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 0.205
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6752
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      start_delay: 2.246
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.8642
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      start_delay: 4.0291
