hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_overtake_robot_low_1895503902
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -5.0
        y: -8.15
      3:
        x: -2.0
        y: -8.18
      4:
        x: 0.0
        y: -7.85
      5:
        x: 2.6
        y: -8.15
      6:
        x: 5.0
        y: -8.15
      7:
        x: 10.0
        y: -8.15
      8:
        x: -13.53
        y: -7.1
      9:
        x: -13.53
        y: -7.4
      10:
        x: -13.53
        y: -8.15
      11:
        x: -14.0
        y: -8.15
      12:
        x: -10.0
        y: -7.85
      13:
        x: -5.0
        y: -8.15
      14:
        x: -2.0
        y: -8.18
      15:
        x: 0.0
        y: -7.85
      16:
        x: 2.6
        y: -8.15
      17:
        x: 5.0
        y: -8.15
      18:
        x: 6.07
        y: -8.15
      19:
        x: 6.07
        y: -8.6
      20:
        x: 6.07
        y: -8.9
      21:
        x: 7.05
        y: -10.6
      22:
        x: -3.73
        y: -8.9
      23:
        x: -3.73
        y: -8.6
      24:
        x: -3.73
        y: -8.15
      25:
        x: -5.0
        y: -8.15
      26:
        x: -2.0
        y: -8.18
      27:
        x: 0.0
        y: -7.85
      28:
        x: 2.6
        y: -8.15
      29:
        x: 5.0
        y: -8.15
      30:
        x: 10.0
        y: -8.15
      31:
        x: 15.0
        y: -8.15
      32:
        x: 15.0
        y: -4.0
      33:
        x: 7.0
        y: -4.0
      34:
        x: 7.0
        y: -2.0
      35:
        x: 7.0
        y: 0.0
      36:
        x: 15.0
        y: 0.0
      37:
        x: 15.0
        y: 2.55
      38:
        x: 15.0
        y: 3.5
      39:
        x: 15.0
        y: 8.0
      40:
        x: 15.0
        y: 9.8
      41:
        x: 15.0
        y: 10.65
      42:
        x: 15.0
        y: 10.8733
      43:
        x: 15.6
        y: 10.8733
      44:
        x: 15.9
        y: 10.8733
      45:
        x: 17.6
        y: 11.7667
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8569
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -13.9991
        y: -8.16195
        z: 0.0
        h: 0.07486
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      start_delay: 0.2139
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.7404
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      start_delay: 2.4795
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.9154
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      start_delay: 3.4989
