hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_conversation_group_high_1167254228
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 8.0
      2:
        x: 15.0
        y: 9.8
      3:
        x: 15.0
        y: 10.65
      4:
        x: 15.0
        y: 12.3
      5:
        x: 15.0
        y: 13.5
      6:
        x: 15.0
        y: 8.0
      7:
        x: 15.0
        y: 9.8
      8:
        x: 15.0
        y: 10.65
      9:
        x: 15.0
        y: 12.3
      10:
        x: 15.0
        y: 13.5
      11:
        x: 15.0
        y: 8.0
      12:
        x: 15.0
        y: 9.8
      13:
        x: 15.0
        y: 10.65
      14:
        x: 15.0
        y: 12.3
      15:
        x: 15.0
        y: 13.5
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 9.8
      18:
        x: 15.0
        y: 10.65
      19:
        x: 15.0
        y: 12.3
      20:
        x: 15.0
        y: 13.5
      21:
        x: 15.9
        y: 6.4067
      22:
        x: 15.6
        y: 6.4067
      23:
        x: 15.0
        y: 6.4067
      24:
        x: 15.0
        y: 8.0
      25:
        x: 15.0
        y: 3.5
      26:
        x: 15.0
        y: 2.55
      27:
        x: 15.0
        y: 0.0
      28:
        x: 7.0
        y: 0.0
      29:
        x: 7.0
        y: -2.0
      30:
        x: 7.0
        y: -4.0
      31:
        x: 15.0
        y: -4.0
      32:
        x: 15.0
        y: -8.15
      33:
        x: 10.0
        y: -8.15
      34:
        x: 5.0
        y: -8.15
      35:
        x: 2.6
        y: -8.15
      36:
        x: 0.0
        y: -7.85
      37:
        x: 1.17
        y: -8.15
      38:
        x: 1.17
        y: -8.6
      39:
        x: 1.17
        y: -8.9
      40:
        x: 2.15
        y: -10.6
      41:
        x: -8.63
        y: -8.9
      42:
        x: -8.63
        y: -8.6
      43:
        x: -8.63
        y: -8.15
      44:
        x: -10.0
        y: -7.85
      45:
        x: -5.0
        y: -8.15
      46:
        x: -2.0
        y: -8.18
      47:
        x: 0.0
        y: -7.85
      48:
        x: 2.6
        y: -8.15
      49:
        x: 5.0
        y: -8.15
      50:
        x: 10.0
        y: -8.15
      51:
        x: 15.0
        y: -8.15
      52:
        x: 15.0
        y: -4.0
      53:
        x: 7.0
        y: -4.0
      54:
        x: 7.0
        y: -2.0
      55:
        x: 7.0
        y: 0.0
      56:
        x: 15.0
        y: 0.0
      57:
        x: 15.0
        y: 2.55
      58:
        x: 15.0
        y: 3.5
      59:
        x: 15.0
        y: 8.0
      60:
        x: 15.0
        y: 9.8
      61:
        x: 15.0
        y: 10.65
      62:
        x: 15.0
        y: 10.8733
      63:
        x: 15.6
        y: 10.8733
      64:
        x: 15.9
        y: 10.8733
      65:
        x: 17.6
        y: 11.7667
      66:
        x: -3.73
        y: -7.1
      67:
        x: -3.73
        y: -7.4
      68:
        x: -3.73
        y: -8.15
      69:
        x: -5.0
        y: -8.15
      70:
        x: -2.0
        y: -8.18
      71:
        x: 0.0
        y: -7.85
      72:
        x: 2.6
        y: -8.15
      73:
        x: 5.0
        y: -8.15
      74:
        x: 10.0
        y: -8.15
      75:
        x: 15.0
        y: -8.15
      76:
        x: 15.0
        y: -4.0
      77:
        x: 7.0
        y: -4.0
      78:
        x: 7.0
        y: -2.0
      79:
        x: 7.0
        y: 0.0
      80:
        x: 15.0
        y: 0.0
      81:
        x: 15.0
        y: 2.55
      82:
        x: 15.0
        y: 3.5
      83:
        x: 15.0
        y: 8.0
      84:
        x: 15.0
        y: 9.8
      85:
        x: 15.0
        y: 10.65
      86:
        x: 15.0
        y: 10.71
      87:
        x: 14.4
        y: 10.71
      88:
        x: 14.1
        y: 10.71
      89:
        x: 12.4
        y: 11.65
      90:
        x: 14.1
        y: 6.01
      91:
        x: 14.4
        y: 6.01
      92:
        x: 15.0
        y: 6.01
      93:
        x: 15.0
        y: 8.0
      94:
        x: 15.0
        y: 3.5
      95:
        x: 15.0
        y: 2.55
      96:
        x: 15.0
        y: 0.0
      97:
        x: 7.0
        y: 0.0
      98:
        x: 7.0
        y: -2.0
      99:
        x: 7.0
        y: -4.0
      100:
        x: 15.0
        y: -4.0
      101:
        x: 15.0
        y: -8.15
      102:
        x: 10.0
        y: -8.15
      103:
        x: 5.0
        y: -8.15
      104:
        x: 2.6
        y: -8.15
      105:
        x: 0.0
        y: -7.85
      106:
        x: -2.0
        y: -8.18
      107:
        x: -5.0
        y: -8.15
      108:
        x: -10.0
        y: -7.85
      109:
        x: -8.63
        y: -8.15
      110:
        x: -8.63
        y: -7.4
      111:
        x: -8.63
        y: -7.1
      112:
        x: -7.65
        y: -5.4
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.5853
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.02422
        y: 5.54773
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 40.3485
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.9593
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.97847
        y: 6.11591
        z: 0.0
        h: 1.570796
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      start_delay: 44.3838
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.9293
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.99457
        y: 6.68409
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 11
      - 12
      - 13
      - 14
      - 15
      start_delay: 43.1639
    event_agent_4:
      id: 4
      group_id: 1
      skin: 3
      max_vel: 0.9671
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.98251
        y: 7.25227
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 39.5805
    background_agent_1:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6538
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      start_delay: 2.7366
    background_agent_2:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.9127
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      start_delay: 1.7907
    background_agent_3:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.7643
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      start_delay: 2.7191
    background_agent_4:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.9424
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      start_delay: 1.4792
