hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_conversation_group_low_2105206038
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 8.0
      2:
        x: 15.0
        y: 9.8
      3:
        x: 15.0
        y: 10.65
      4:
        x: 15.0
        y: 12.3
      5:
        x: 15.0
        y: 13.5
      6:
        x: 15.0
        y: 8.0
      7:
        x: 15.0
        y: 9.8
      8:
        x: 15.0
        y: 10.65
      9:
        x: 15.0
        y: 12.3
      10:
        x: 15.0
        y: 13.5
      11:
        x: 14.1
        y: 10.71
      12:
        x: 14.4
        y: 10.71
      13:
        x: 15.0
        y: 10.71
      14:
        x: 15.0
        y: 10.65
      15:
        x: 15.0
        y: 9.8
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 6.4067
      18:
        x: 15.6
        y: 6.4067
      19:
        x: 15.9
        y: 6.4067
      20:
        x: 17.6
        y: 7.3
    agents:
    - event_agent_1
    - event_agent_2
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.7075
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.01113
        y: 6.11396
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 38.815
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.9035
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.98849
        y: 6.68604
        z: 0.0
        h: 1.570796
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      start_delay: 38.9308
    background_agent_1:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6554
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 1.468
