hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_crossing_low_842874859
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 14.1
        y: 6.01
      2:
        x: 14.4
        y: 6.01
      3:
        x: 15.0
        y: 6.01
      4:
        x: 15.0
        y: 8.0
      5:
        x: 15.0
        y: 6.4067
      6:
        x: 15.6
        y: 6.4067
      7:
        x: 15.9
        y: 6.4067
      8:
        x: 17.6
        y: 7.3
      9:
        x: 1.17
        y: -8.9
      10:
        x: 1.17
        y: -8.6
      11:
        x: 1.17
        y: -8.15
      12:
        x: 0.0
        y: -7.85
      13:
        x: -2.0
        y: -8.18
      14:
        x: -5.0
        y: -8.15
      15:
        x: -10.0
        y: -7.85
      16:
        x: -8.63
        y: -8.15
      17:
        x: -8.63
        y: -8.6
      18:
        x: -8.63
        y: -8.9
      19:
        x: -7.65
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.9698
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 5.0805
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9906
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      start_delay: 1.9747
