hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_narrow_passing_high_775762057
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -14.0
        y: -8.15
      3:
        x: 14.1
        y: 10.71
      4:
        x: 14.4
        y: 10.71
      5:
        x: 15.0
        y: 10.71
      6:
        x: 15.0
        y: 10.65
      7:
        x: 15.0
        y: 9.8
      8:
        x: 15.0
        y: 8.0
      9:
        x: 15.0
        y: 3.5
      10:
        x: 15.0
        y: 2.55
      11:
        x: 15.0
        y: 0.0
      12:
        x: 7.0
        y: 0.0
      13:
        x: 7.0
        y: -2.0
      14:
        x: 7.0
        y: -4.0
      15:
        x: 15.0
        y: -4.0
      16:
        x: 15.0
        y: -8.15
      17:
        x: 10.0
        y: -8.15
      18:
        x: 5.0
        y: -8.15
      19:
        x: 2.6
        y: -8.15
      20:
        x: 0.0
        y: -7.85
      21:
        x: 1.17
        y: -8.15
      22:
        x: 1.17
        y: -7.4
      23:
        x: 1.17
        y: -7.1
      24:
        x: 2.15
        y: -5.4
      25:
        x: 10.97
        y: -8.9
      26:
        x: 10.97
        y: -8.6
      27:
        x: 10.97
        y: -8.15
      28:
        x: 10.0
        y: -8.15
      29:
        x: 5.0
        y: -8.15
      30:
        x: 2.6
        y: -8.15
      31:
        x: 0.0
        y: -7.85
      32:
        x: -2.0
        y: -8.18
      33:
        x: -5.0
        y: -8.15
      34:
        x: -3.73
        y: -8.15
      35:
        x: -3.73
        y: -7.4
      36:
        x: -3.73
        y: -7.1
      37:
        x: -2.75
        y: -5.4
      38:
        x: -8.63
        y: -7.1
      39:
        x: -8.63
        y: -7.4
      40:
        x: -8.63
        y: -8.15
      41:
        x: -10.0
        y: -7.85
      42:
        x: -5.0
        y: -8.15
      43:
        x: -2.0
        y: -8.18
      44:
        x: 0.0
        y: -7.85
      45:
        x: 2.6
        y: -8.15
      46:
        x: 5.0
        y: -8.15
      47:
        x: 10.0
        y: -8.15
      48:
        x: 15.0
        y: -8.15
      49:
        x: 15.0
        y: -4.0
      50:
        x: 7.0
        y: -4.0
      51:
        x: 7.0
        y: -2.0
      52:
        x: 7.0
        y: 0.0
      53:
        x: 15.0
        y: 0.0
      54:
        x: 15.0
        y: 2.55
      55:
        x: 15.0
        y: 3.5
      56:
        x: 15.0
        y: 8.0
      57:
        x: 15.0
        y: 9.8
      58:
        x: 15.0
        y: 10.65
      59:
        x: 15.0
        y: 10.8733
      60:
        x: 15.6
        y: 10.8733
      61:
        x: 15.9
        y: 10.8733
      62:
        x: 17.6
        y: 11.7667
      63:
        x: 1.17
        y: -8.9
      64:
        x: 1.17
        y: -8.6
      65:
        x: 1.17
        y: -8.15
      66:
        x: 0.0
        y: -7.85
      67:
        x: -2.0
        y: -8.18
      68:
        x: -5.0
        y: -8.15
      69:
        x: -10.0
        y: -7.85
      70:
        x: -8.63
        y: -8.15
      71:
        x: -8.63
        y: -8.6
      72:
        x: -8.63
        y: -8.9
      73:
        x: -7.65
        y: -10.6
      74:
        x: -3.73
        y: -8.9
      75:
        x: -3.73
        y: -8.6
      76:
        x: -3.73
        y: -8.15
      77:
        x: -5.0
        y: -8.15
      78:
        x: -2.0
        y: -8.18
      79:
        x: 0.0
        y: -7.85
      80:
        x: 2.6
        y: -8.15
      81:
        x: 5.0
        y: -8.15
      82:
        x: 10.0
        y: -8.15
      83:
        x: 15.0
        y: -8.15
      84:
        x: 15.0
        y: -4.0
      85:
        x: 7.0
        y: -4.0
      86:
        x: 7.0
        y: -2.0
      87:
        x: 7.0
        y: 0.0
      88:
        x: 15.0
        y: 0.0
      89:
        x: 15.0
        y: 2.55
      90:
        x: 15.0
        y: 1.94
      91:
        x: 15.6
        y: 1.94
      92:
        x: 15.9
        y: 1.94
      93:
        x: 17.6
        y: 2.8333
      94:
        x: 6.07
        y: -8.9
      95:
        x: 6.07
        y: -8.6
      96:
        x: 6.07
        y: -8.15
      97:
        x: 5.0
        y: -8.15
      98:
        x: 2.6
        y: -8.15
      99:
        x: 0.0
        y: -7.85
      100:
        x: -2.0
        y: -8.18
      101:
        x: -5.0
        y: -8.15
      102:
        x: -3.73
        y: -8.15
      103:
        x: -3.73
        y: -7.4
      104:
        x: -3.73
        y: -7.1
      105:
        x: -2.75
        y: -5.4
      106:
        x: 15.9
        y: 10.8733
      107:
        x: 15.6
        y: 10.8733
      108:
        x: 15.0
        y: 10.8733
      109:
        x: 15.0
        y: 10.65
      110:
        x: 15.0
        y: 9.8
      111:
        x: 15.0
        y: 8.0
      112:
        x: 15.0
        y: 6.4067
      113:
        x: 15.6
        y: 6.4067
      114:
        x: 15.9
        y: 6.4067
      115:
        x: 17.6
        y: 7.3
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.5631
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -4.99934
        y: -8.13896
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 0.6372
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6417
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      start_delay: 1.3508
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.8147
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      start_delay: 2.6124
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.8858
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      start_delay: 4.315
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6589
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      start_delay: 0.4964
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.8788
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      start_delay: 0.1176
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8354
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      start_delay: 4.4916
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.8127
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      start_delay: 3.915
