hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_crossing_group_low_624501492
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.9
        y: 6.4067
      2:
        x: 15.6
        y: 6.4067
      3:
        x: 15.0
        y: 6.4067
      4:
        x: 15.0
        y: 8.0
      5:
        x: 15.0
        y: 6.01
      6:
        x: 14.4
        y: 6.01
      7:
        x: 14.1
        y: 6.01
      8:
        x: 12.4
        y: 6.95
      9:
        x: 15.9
        y: 6.4067
      10:
        x: 15.6
        y: 6.4067
      11:
        x: 15.0
        y: 6.4067
      12:
        x: 15.0
        y: 8.0
      13:
        x: 15.0
        y: 6.01
      14:
        x: 14.4
        y: 6.01
      15:
        x: 14.1
        y: 6.01
      16:
        x: 12.4
        y: 6.95
    agents:
    - event_agent_1
    - event_agent_2
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.7439
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.59279
        y: 7.31371
        z: 0.0
        h: -2.657777
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 4.0968
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.7439
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.07775
        y: 7.03272
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      start_delay: 4.0968
