hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_opposing_group_low_306007513
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -14.0
        y: -8.15
      3:
        x: -10.0
        y: -7.85
      4:
        x: -14.0
        y: -8.15
      5:
        x: -10.0
        y: -7.85
      6:
        x: -14.0
        y: -8.15
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.8441
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -5.001
        y: -8.16664
        z: 0.0
        h: 3.081664
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 0.7204
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.8441
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -5.59912
        y: -8.11495
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      start_delay: 0.7204
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.8441
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -6.19962
        y: -8.10294
        z: 0.0
        h: 3.081664
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      start_delay: 0.7204
