hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_sudden_entry_high_1208585901
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 1.17
        y: -8.6
      2:
        x: 1.17
        y: -8.15
      3:
        x: 0.0
        y: -7.85
      4:
        x: 2.6
        y: -8.15
      5:
        x: -8.63
        y: -8.9
      6:
        x: -8.63
        y: -8.6
      7:
        x: -8.63
        y: -8.15
      8:
        x: -10.0
        y: -7.85
      9:
        x: -5.0
        y: -8.15
      10:
        x: -2.0
        y: -8.18
      11:
        x: 0.0
        y: -7.85
      12:
        x: 2.6
        y: -8.15
      13:
        x: 5.0
        y: -8.15
      14:
        x: 10.0
        y: -8.15
      15:
        x: 10.97
        y: -8.15
      16:
        x: 10.97
        y: -8.6
      17:
        x: 10.97
        y: -8.9
      18:
        x: 11.95
        y: -10.6
      19:
        x: 1.17
        y: -7.1
      20:
        x: 1.17
        y: -7.4
      21:
        x: 1.17
        y: -8.15
      22:
        x: 0.0
        y: -7.85
      23:
        x: -2.0
        y: -8.18
      24:
        x: -5.0
        y: -8.15
      25:
        x: -10.0
        y: -7.85
      26:
        x: -8.63
        y: -8.15
      27:
        x: -8.63
        y: -8.6
      28:
        x: -8.63
        y: -8.9
      29:
        x: -7.65
        y: -10.6
      30:
        x: 15.9
        y: 6.4067
      31:
        x: 15.6
        y: 6.4067
      32:
        x: 15.0
        y: 6.4067
      33:
        x: 15.0
        y: 8.0
      34:
        x: 15.0
        y: 3.5
      35:
        x: 15.0
        y: 2.55
      36:
        x: 15.0
        y: 0.0
      37:
        x: 7.0
        y: 0.0
      38:
        x: 7.0
        y: -2.0
      39:
        x: 7.0
        y: -4.0
      40:
        x: 15.0
        y: -4.0
      41:
        x: 15.0
        y: -8.15
      42:
        x: 10.0
        y: -8.15
      43:
        x: 5.0
        y: -8.15
      44:
        x: 2.6
        y: -8.15
      45:
        x: 0.0
        y: -7.85
      46:
        x: -2.0
        y: -8.18
      47:
        x: -5.0
        y: -8.15
      48:
        x: -10.0
        y: -7.85
      49:
        x: -8.63
        y: -8.15
      50:
        x: -8.63
        y: -7.4
      51:
        x: -8.63
        y: -7.1
      52:
        x: -7.65
        y: -5.4
      53:
        x: -3.73
        y: -7.1
      54:
        x: -3.73
        y: -7.4
      55:
        x: -3.73
        y: -8.15
      56:
        x: -5.0
        y: -8.15
      57:
        x: -2.0
        y: -8.18
      58:
        x: 0.0
        y: -7.85
      59:
        x: 2.6
        y: -8.15
      60:
        x: 5.0
        y: -8.15
      61:
        x: 6.07
        y: -8.15
      62:
        x: 6.07
        y: -8.6
      63:
        x: 6.07
        y: -8.9
      64:
        x: 7.05
        y: -10.6
      65:
        x: 1.17
        y: -8.9
      66:
        x: 1.17
        y: -8.6
      67:
        x: 1.17
        y: -8.15
      68:
        x: 0.0
        y: -7.85
      69:
        x: 2.6
        y: -8.15
      70:
        x: 5.0
        y: -8.15
      71:
        x: 10.0
        y: -8.15
      72:
        x: 15.0
        y: -8.15
      73:
        x: 15.0
        y: -4.0
      74:
        x: 7.0
        y: -4.0
      75:
        x: 7.0
        y: -2.0
      76:
        x: 7.0
        y: 0.0
      77:
        x: 15.0
        y: 0.0
      78:
        x: 15.0
        y: 2.55
      79:
        x: 15.0
        y: 3.5
      80:
        x: 15.0
        y: 8.0
      81:
        x: 15.0
        y: 9.8
      82:
        x: 15.0
        y: 10.65
      83:
        x: 15.0
        y: 10.8733
      84:
        x: 15.6
        y: 10.8733
      85:
        x: 15.9
        y: 10.8733
      86:
        x: 17.6
        y: 11.7667
      87:
        x: 15.9
        y: 10.8733
      88:
        x: 15.6
        y: 10.8733
      89:
        x: 15.0
        y: 10.8733
      90:
        x: 15.0
        y: 10.65
      91:
        x: 15.0
        y: 9.8
      92:
        x: 15.0
        y: 8.0
      93:
        x: 15.0
        y: 3.5
      94:
        x: 15.0
        y: 2.55
      95:
        x: 15.0
        y: 0.0
      96:
        x: 7.0
        y: 0.0
      97:
        x: 7.0
        y: -2.0
      98:
        x: 7.0
        y: -4.0
      99:
        x: 15.0
        y: -4.0
      100:
        x: 15.0
        y: -8.15
      101:
        x: 10.0
        y: -8.15
      102:
        x: 5.0
        y: -8.15
      103:
        x: 2.6
        y: -8.15
      104:
        x: 0.0
        y: -7.85
      105:
        x: -2.0
        y: -8.18
      106:
        x: -5.0
        y: -8.15
      107:
        x: -10.0
        y: -7.85
      108:
        x: -14.0
        y: -8.15
      109:
        x: -13.53
        y: -8.15
      110:
        x: -13.53
        y: -7.4
      111:
        x: -13.53
        y: -7.1
      112:
        x: -12.55
        y: -5.4
      113:
        x: 6.07
        y: -8.9
      114:
        x: 6.07
        y: -8.6
      115:
        x: 6.07
        y: -8.15
      116:
        x: 5.0
        y: -8.15
      117:
        x: 10.0
        y: -8.15
      118:
        x: 15.0
        y: -8.15
      119:
        x: 15.0
        y: -4.0
      120:
        x: 7.0
        y: -4.0
      121:
        x: 7.0
        y: -2.0
      122:
        x: 7.0
        y: 0.0
      123:
        x: 15.0
        y: 0.0
      124:
        x: 15.0
        y: 2.55
      125:
        x: 15.0
        y: 1.94
      126:
        x: 15.6
        y: 1.94
      127:
        x: 15.9
        y: 1.94
      128:
        x: 17.6
        y: 2.8333
      129:
        x: -3.73
        y: -8.9
      130:
        x: -3.73
        y: -8.6
      131:
        x: -3.73
        y: -8.15
      132:
        x: -5.0
        y: -8.15
      133:
        x: -2.0
        y: -8.18
      134:
        x: 0.0
        y: -7.85
      135:
        x: 2.6
        y: -8.15
      136:
        x: 5.0
        y: -8.15
      137:
        x: 10.0
        y: -8.15
      138:
        x: 15.0
        y: -8.15
      139:
        x: 15.0
        y: -4.0
      140:
        x: 7.0
        y: -4.0
      141:
        x: 7.0
        y: -2.0
      142:
        x: 7.0
        y: 0.0
      143:
        x: 15.0
        y: 0.0
      144:
        x: 15.0
        y: 2.55
      145:
        x: 15.0
        y: 1.94
      146:
        x: 15.6
        y: 1.94
      147:
        x: 15.9
        y: 1.94
      148:
        x: 17.6
        y: 2.8333
      149:
        x: -13.53
        y: -8.9
      150:
        x: -13.53
        y: -8.6
      151:
        x: -13.53
        y: -8.15
      152:
        x: -14.0
        y: -8.15
      153:
        x: -10.0
        y: -7.85
      154:
        x: -5.0
        y: -8.15
      155:
        x: -3.73
        y: -8.15
      156:
        x: -3.73
        y: -8.6
      157:
        x: -3.73
        y: -8.9
      158:
        x: -2.75
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8115
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 1.17
        y: -8.9
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 1.605
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.7819
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      start_delay: 0.0997
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.8591
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      start_delay: 2.2964
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.5743
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      start_delay: 2.1324
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.9702
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      start_delay: 3.0074
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.6764
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      start_delay: 1.8702
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.5677
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      start_delay: 1.1449
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.9765
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      start_delay: 1.1839
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.7247
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      - 146
      - 147
      - 148
      start_delay: 4.9828
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.9295
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 149
      - 150
      - 151
      - 152
      - 153
      - 154
      - 155
      - 156
      - 157
      - 158
      start_delay: 0.7295
