hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_door_bottleneck_high_374153818
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 14.1
        y: 6.01
      2:
        x: 14.4
        y: 6.01
      3:
        x: 15.0
        y: 6.01
      4:
        x: 15.0
        y: 8.0
      5:
        x: 15.0
        y: 9.8
      6:
        x: -8.63
        y: -7.1
      7:
        x: -8.63
        y: -7.4
      8:
        x: -8.63
        y: -8.15
      9:
        x: -10.0
        y: -7.85
      10:
        x: -5.0
        y: -8.15
      11:
        x: -2.0
        y: -8.18
      12:
        x: 0.0
        y: -7.85
      13:
        x: 2.6
        y: -8.15
      14:
        x: 5.0
        y: -8.15
      15:
        x: 10.0
        y: -8.15
      16:
        x: 15.0
        y: -8.15
      17:
        x: 15.0
        y: -4.0
      18:
        x: 7.0
        y: -4.0
      19:
        x: 7.0
        y: -2.0
      20:
        x: 7.0
        y: 0.0
      21:
        x: 15.0
        y: 0.0
      22:
        x: 15.0
        y: 2.55
      23:
        x: 15.0
        y: 3.5
      24:
        x: 15.0
        y: 8.0
      25:
        x: 15.0
        y: 9.8
      26:
        x: 15.0
        y: 10.65
      27:
        x: 15.0
        y: 10.8733
      28:
        x: 15.6
        y: 10.8733
      29:
        x: 15.9
        y: 10.8733
      30:
        x: 17.6
        y: 11.7667
      31:
        x: 1.17
        y: -7.1
      32:
        x: 1.17
        y: -7.4
      33:
        x: 1.17
        y: -8.15
      34:
        x: 0.0
        y: -7.85
      35:
        x: 2.6
        y: -8.15
      36:
        x: 5.0
        y: -8.15
      37:
        x: 10.0
        y: -8.15
      38:
        x: 15.0
        y: -8.15
      39:
        x: 15.0
        y: -4.0
      40:
        x: 7.0
        y: -4.0
      41:
        x: 7.0
        y: -2.0
      42:
        x: 7.0
        y: 0.0
      43:
        x: 15.0
        y: 0.0
      44:
        x: 15.0
        y: 2.55
      45:
        x: 15.0
        y: 1.94
      46:
        x: 15.6
        y: 1.94
      47:
        x: 15.9
        y: 1.94
      48:
        x: 17.6
        y: 2.8333
      49:
        x: 6.07
        y: -8.9
      50:
        x: 6.07
        y: -8.6
      51:
        x: 6.07
        y: -8.15
      52:
        x: 5.0
        y: -8.15
      53:
        x: 2.6
        y: -8.15
      54:
        x: 0.0
        y: -7.85
      55:
        x: -2.0
        y: -8.18
      56:
        x: -5.0
        y: -8.15
      57:
        x: -3.73
        y: -8.15
      58:
        x: -3.73
        y: -7.4
      59:
        x: -3.73
        y: -7.1
      60:
        x: -2.75
        y: -5.4
      61:
        x: -3.73
        y: -8.9
      62:
        x: -3.73
        y: -8.6
      63:
        x: -3.73
        y: -8.15
      64:
        x: -5.0
        y: -8.15
      65:
        x: -10.0
        y: -7.85
      66:
        x: -8.63
        y: -8.15
      67:
        x: -8.63
        y: -7.4
      68:
        x: -8.63
        y: -7.1
      69:
        x: -7.65
        y: -5.4
      70:
        x: 10.97
        y: -8.9
      71:
        x: 10.97
        y: -8.6
      72:
        x: 10.97
        y: -8.15
      73:
        x: 10.0
        y: -8.15
      74:
        x: 15.0
        y: -8.15
      75:
        x: 15.0
        y: -4.0
      76:
        x: 7.0
        y: -4.0
      77:
        x: 7.0
        y: -2.0
      78:
        x: 7.0
        y: 0.0
      79:
        x: 15.0
        y: 0.0
      80:
        x: 15.0
        y: 2.55
      81:
        x: 15.0
        y: 3.5
      82:
        x: 15.0
        y: 8.0
      83:
        x: 15.0
        y: 9.8
      84:
        x: 15.0
        y: 10.65
      85:
        x: 15.0
        y: 10.8733
      86:
        x: 15.6
        y: 10.8733
      87:
        x: 15.9
        y: 10.8733
      88:
        x: 17.6
        y: 11.7667
      89:
        x: -8.63
        y: -8.9
      90:
        x: -8.63
        y: -8.6
      91:
        x: -8.63
        y: -8.15
      92:
        x: -10.0
        y: -7.85
      93:
        x: -5.0
        y: -8.15
      94:
        x: -2.0
        y: -8.18
      95:
        x: 0.0
        y: -7.85
      96:
        x: 2.6
        y: -8.15
      97:
        x: 5.0
        y: -8.15
      98:
        x: 10.0
        y: -8.15
      99:
        x: 15.0
        y: -8.15
      100:
        x: 15.0
        y: -4.0
      101:
        x: 7.0
        y: -4.0
      102:
        x: 7.0
        y: -2.0
      103:
        x: 7.0
        y: 0.0
      104:
        x: 15.0
        y: 0.0
      105:
        x: 15.0
        y: 2.55
      106:
        x: 15.0
        y: 3.5
      107:
        x: 15.0
        y: 8.0
      108:
        x: 15.0
        y: 9.8
      109:
        x: 15.0
        y: 10.65
      110:
        x: 15.0
        y: 10.8733
      111:
        x: 15.6
        y: 10.8733
      112:
        x: 15.9
        y: 10.8733
      113:
        x: 17.6
        y: 11.7667
      114:
        x: -13.53
        y: -7.1
      115:
        x: -13.53
        y: -7.4
      116:
        x: -13.53
        y: -8.15
      117:
        x: -14.0
        y: -8.15
      118:
        x: -10.0
        y: -7.85
      119:
        x: -5.0
        y: -8.15
      120:
        x: -2.0
        y: -8.18
      121:
        x: 0.0
        y: -7.85
      122:
        x: 1.17
        y: -8.15
      123:
        x: 1.17
        y: -7.4
      124:
        x: 1.17
        y: -7.1
      125:
        x: 2.15
        y: -5.4
      126:
        x: -3.73
        y: -7.1
      127:
        x: -3.73
        y: -7.4
      128:
        x: -3.73
        y: -8.15
      129:
        x: -5.0
        y: -8.15
      130:
        x: -2.0
        y: -8.18
      131:
        x: 0.0
        y: -7.85
      132:
        x: 2.6
        y: -8.15
      133:
        x: 5.0
        y: -8.15
      134:
        x: 10.0
        y: -8.15
      135:
        x: 15.0
        y: -8.15
      136:
        x: 15.0
        y: -4.0
      137:
        x: 7.0
        y: -4.0
      138:
        x: 7.0
        y: -2.0
      139:
        x: 7.0
        y: 0.0
      140:
        x: 15.0
        y: 0.0
      141:
        x: 15.0
        y: 2.55
      142:
        x: 15.0
        y: 1.94
      143:
        x: 15.6
        y: 1.94
      144:
        x: 15.9
        y: 1.94
      145:
        x: 17.6
        y: 2.8333
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.6744
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 9.2736
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.801
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 4.795
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7569
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      start_delay: 1.3776
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7901
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      start_delay: 0.8734
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.7531
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      start_delay: 4.8102
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7693
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      start_delay: 2.0293
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.7383
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      start_delay: 2.2787
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.7867
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      start_delay: 4.1329
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.9334
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      start_delay: 3.9455
