hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_conversation_group_high_1156875968
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 8.0
      2:
        x: 15.0
        y: 9.8
      3:
        x: 15.0
        y: 10.65
      4:
        x: 15.0
        y: 12.3
      5:
        x: 15.0
        y: 13.5
      6:
        x: 15.0
        y: 8.0
      7:
        x: 15.0
        y: 9.8
      8:
        x: 15.0
        y: 10.65
      9:
        x: 15.0
        y: 12.3
      10:
        x: 15.0
        y: 13.5
      11:
        x: 15.0
        y: 8.0
      12:
        x: 15.0
        y: 9.8
      13:
        x: 15.0
        y: 10.65
      14:
        x: 15.0
        y: 12.3
      15:
        x: 15.0
        y: 13.5
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 9.8
      18:
        x: 15.0
        y: 10.65
      19:
        x: 15.0
        y: 12.3
      20:
        x: 15.0
        y: 13.5
      21:
        x: -8.63
        y: -8.9
      22:
        x: -8.63
        y: -8.6
      23:
        x: -8.63
        y: -8.15
      24:
        x: -10.0
        y: -7.85
      25:
        x: -8.63
        y: -8.15
      26:
        x: -8.63
        y: -7.4
      27:
        x: -8.63
        y: -7.1
      28:
        x: -7.65
        y: -5.4
      29:
        x: 6.07
        y: -8.9
      30:
        x: 6.07
        y: -8.6
      31:
        x: 6.07
        y: -8.15
      32:
        x: 5.0
        y: -8.15
      33:
        x: 2.6
        y: -8.15
      34:
        x: 0.0
        y: -7.85
      35:
        x: 1.17
        y: -8.15
      36:
        x: 1.17
        y: -7.4
      37:
        x: 1.17
        y: -7.1
      38:
        x: 2.15
        y: -5.4
      39:
        x: -3.73
        y: -7.1
      40:
        x: -3.73
        y: -7.4
      41:
        x: -3.73
        y: -8.15
      42:
        x: -5.0
        y: -8.15
      43:
        x: -2.0
        y: -8.18
      44:
        x: 0.0
        y: -7.85
      45:
        x: 1.17
        y: -8.15
      46:
        x: 1.17
        y: -8.6
      47:
        x: 1.17
        y: -8.9
      48:
        x: 2.15
        y: -10.6
      49:
        x: 15.9
        y: 10.8733
      50:
        x: 15.6
        y: 10.8733
      51:
        x: 15.0
        y: 10.8733
      52:
        x: 15.0
        y: 10.65
      53:
        x: 15.0
        y: 9.8
      54:
        x: 15.0
        y: 8.0
      55:
        x: 15.0
        y: 3.5
      56:
        x: 15.0
        y: 2.55
      57:
        x: 15.0
        y: 0.0
      58:
        x: 7.0
        y: 0.0
      59:
        x: 7.0
        y: -2.0
      60:
        x: 7.0
        y: -4.0
      61:
        x: 15.0
        y: -4.0
      62:
        x: 15.0
        y: -8.15
      63:
        x: 10.0
        y: -8.15
      64:
        x: 5.0
        y: -8.15
      65:
        x: 2.6
        y: -8.15
      66:
        x: 0.0
        y: -7.85
      67:
        x: 1.17
        y: -8.15
      68:
        x: 1.17
        y: -7.4
      69:
        x: 1.17
        y: -7.1
      70:
        x: 2.15
        y: -5.4
      71:
        x: -13.53
        y: -7.1
      72:
        x: -13.53
        y: -7.4
      73:
        x: -13.53
        y: -8.15
      74:
        x: -14.0
        y: -8.15
      75:
        x: -10.0
        y: -7.85
      76:
        x: -5.0
        y: -8.15
      77:
        x: -2.0
        y: -8.18
      78:
        x: 0.0
        y: -7.85
      79:
        x: 2.6
        y: -8.15
      80:
        x: 5.0
        y: -8.15
      81:
        x: 10.0
        y: -8.15
      82:
        x: 10.97
        y: -8.15
      83:
        x: 10.97
        y: -8.6
      84:
        x: 10.97
        y: -8.9
      85:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.6947
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.98235
        y: 5.50197
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 43.5398
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.6512
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.0039
        y: 6.10066
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      start_delay: 38.604
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.8526
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.00128
        y: 6.69934
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 11
      - 12
      - 13
      - 14
      - 15
      start_delay: 43.9973
    event_agent_4:
      id: 4
      group_id: 1
      skin: 3
      max_vel: 0.8631
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.01586
        y: 7.29803
        z: 0.0
        h: 1.570796
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 38.0864
    background_agent_1:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.5943
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      start_delay: 4.7048
    background_agent_2:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7346
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      start_delay: 4.7138
    background_agent_3:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8007
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      start_delay: 1.5304
    background_agent_4:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.7852
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      start_delay: 3.8306
    background_agent_5:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.6658
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      start_delay: 2.4471
