hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_sudden_entry_low_901937479
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 1.17
        y: -8.6
      2:
        x: 1.17
        y: -8.15
      3:
        x: 0.0
        y: -7.85
      4:
        x: 2.6
        y: -8.15
      5:
        x: 1.17
        y: -8.9
      6:
        x: 1.17
        y: -8.6
      7:
        x: 1.17
        y: -8.15
      8:
        x: 0.0
        y: -7.85
      9:
        x: -2.0
        y: -8.18
      10:
        x: -5.0
        y: -8.15
      11:
        x: -3.73
        y: -8.15
      12:
        x: -3.73
        y: -7.4
      13:
        x: -3.73
        y: -7.1
      14:
        x: -2.75
        y: -5.4
    agents:
    - event_agent_1
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8409
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 1.17
        y: -8.9
        z: 0.0
        h: 1.570796
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 1.4029
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.8757
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      start_delay: 2.3833
