hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_head_on_low_101
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -5.0
        y: -8.15
      3:
        x: -2.0
        y: -8.18
      4:
        x: 0.0
        y: -7.85
      5:
        x: -3.73
        y: -7.1
      6:
        x: -3.73
        y: -7.4
      7:
        x: -3.73
        y: -8.15
      8:
        x: -5.0
        y: -8.15
      9:
        x: -2.0
        y: -8.18
      10:
        x: 0.0
        y: -7.85
      11:
        x: 2.6
        y: -8.15
      12:
        x: 5.0
        y: -8.15
      13:
        x: 10.0
        y: -8.15
      14:
        x: 15.0
        y: -8.15
      15:
        x: 15.0
        y: -4.0
      16:
        x: 7.0
        y: -4.0
      17:
        x: 7.0
        y: -2.0
      18:
        x: 7.0
        y: 0.0
      19:
        x: 15.0
        y: 0.0
      20:
        x: 15.0
        y: 2.55
      21:
        x: 15.0
        y: 3.5
      22:
        x: 15.0
        y: 8.0
      23:
        x: 15.0
        y: 6.01
      24:
        x: 14.4
        y: 6.01
      25:
        x: 14.1
        y: 6.01
      26:
        x: 12.4
        y: 6.95
    agents:
    - event_agent_1
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.7766
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -13.99595
        y: -8.20403
        z: 0.0
        h: 0.07486
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 1.2041
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.8368
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      start_delay: 1.6301
