hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_mixed_interaction_high_804427682
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 12.3
      2:
        x: 15.0
        y: 10.65
      3:
        x: 15.0
        y: 9.8
      4:
        x: 15.0
        y: 8.0
      5:
        x: 15.0
        y: 3.5
      6:
        x: 15.0
        y: 2.55
      7:
        x: 10.97
        y: -8.9
      8:
        x: 10.97
        y: -8.6
      9:
        x: 10.97
        y: -8.15
      10:
        x: 10.0
        y: -8.15
      11:
        x: 5.0
        y: -8.15
      12:
        x: 2.6
        y: -8.15
      13:
        x: 0.0
        y: -7.85
      14:
        x: -2.0
        y: -8.18
      15:
        x: -5.0
        y: -8.15
      16:
        x: -10.0
        y: -7.85
      17:
        x: -8.63
        y: -8.15
      18:
        x: -8.63
        y: -8.6
      19:
        x: -8.63
        y: -8.9
      20:
        x: -7.65
        y: -10.6
      21:
        x: 14.1
        y: 10.71
      22:
        x: 14.4
        y: 10.71
      23:
        x: 15.0
        y: 10.71
      24:
        x: 15.0
        y: 10.65
      25:
        x: 15.0
        y: 9.8
      26:
        x: 15.0
        y: 8.0
      27:
        x: 15.0
        y: 6.4067
      28:
        x: 15.6
        y: 6.4067
      29:
        x: 15.9
        y: 6.4067
      30:
        x: 17.6
        y: 7.3
      31:
        x: -3.73
        y: -7.1
      32:
        x: -3.73
        y: -7.4
      33:
        x: -3.73
        y: -8.15
      34:
        x: -5.0
        y: -8.15
      35:
        x: -2.0
        y: -8.18
      36:
        x: 0.0
        y: -7.85
      37:
        x: 1.17
        y: -8.15
      38:
        x: 1.17
        y: -7.4
      39:
        x: 1.17
        y: -7.1
      40:
        x: 2.15
        y: -5.4
      41:
        x: -8.63
        y: -7.1
      42:
        x: -8.63
        y: -7.4
      43:
        x: -8.63
        y: -8.15
      44:
        x: -10.0
        y: -7.85
      45:
        x: -14.0
        y: -8.15
      46:
        x: -13.53
        y: -8.15
      47:
        x: -13.53
        y: -8.6
      48:
        x: -13.53
        y: -8.9
      49:
        x: -12.55
        y: -10.6
      50:
        x: 15.9
        y: 1.94
      51:
        x: 15.6
        y: 1.94
      52:
        x: 15.0
        y: 1.94
      53:
        x: 15.0
        y: 2.55
      54:
        x: 15.0
        y: 0.0
      55:
        x: 7.0
        y: 0.0
      56:
        x: 7.0
        y: -2.0
      57:
        x: 7.0
        y: -4.0
      58:
        x: 15.0
        y: -4.0
      59:
        x: 15.0
        y: -8.15
      60:
        x: 10.0
        y: -8.15
      61:
        x: 5.0
        y: -8.15
      62:
        x: 2.6
        y: -8.15
      63:
        x: 0.0
        y: -7.85
      64:
        x: 1.17
        y: -8.15
      65:
        x: 1.17
        y: -7.4
      66:
        x: 1.17
        y: -7.1
      67:
        x: 2.15
        y: -5.4
      68:
        x: 1.17
        y: -7.1
      69:
        x: 1.17
        y: -7.4
      70:
        x: 1.17
        y: -8.15
      71:
        x: 0.0
        y: -7.85
      72:
        x: 2.6
        y: -8.15
      73:
        x: 5.0
        y: -8.15
      74:
        x: 10.0
        y: -8.15
      75:
        x: 15.0
        y: -8.15
      76:
        x: 15.0
        y: -4.0
      77:
        x: 7.0
        y: -4.0
      78:
        x: 7.0
        y: -2.0
      79:
        x: 7.0
        y: 0.0
      80:
        x: 15.0
        y: 0.0
      81:
        x: 15.0
        y: 2.55
      82:
        x: 15.0
        y: 1.94
      83:
        x: 15.6
        y: 1.94
      84:
        x: 15.9
        y: 1.94
      85:
        x: 17.6
        y: 2.8333
      86:
        x: 15.9
        y: 10.8733
      87:
        x: 15.6
        y: 10.8733
      88:
        x: 15.0
        y: 10.8733
      89:
        x: 15.0
        y: 10.65
      90:
        x: 15.0
        y: 9.8
      91:
        x: 15.0
        y: 8.0
      92:
        x: 15.0
        y: 3.5
      93:
        x: 15.0
        y: 2.55
      94:
        x: 15.0
        y: 0.0
      95:
        x: 7.0
        y: 0.0
      96:
        x: 7.0
        y: -2.0
      97:
        x: 7.0
        y: -4.0
      98:
        x: 15.0
        y: -4.0
      99:
        x: 15.0
        y: -8.15
      100:
        x: 10.0
        y: -8.15
      101:
        x: 5.0
        y: -8.15
      102:
        x: 2.6
        y: -8.15
      103:
        x: 0.0
        y: -7.85
      104:
        x: -2.0
        y: -8.18
      105:
        x: -5.0
        y: -8.15
      106:
        x: -3.73
        y: -8.15
      107:
        x: -3.73
        y: -8.6
      108:
        x: -3.73
        y: -8.9
      109:
        x: -2.75
        y: -10.6
      110:
        x: 15.9
        y: 6.4067
      111:
        x: 15.6
        y: 6.4067
      112:
        x: 15.0
        y: 6.4067
      113:
        x: 15.0
        y: 8.0
      114:
        x: 15.0
        y: 3.5
      115:
        x: 15.0
        y: 2.55
      116:
        x: 15.0
        y: 1.94
      117:
        x: 15.6
        y: 1.94
      118:
        x: 15.9
        y: 1.94
      119:
        x: 17.6
        y: 2.8333
      120:
        x: -13.53
        y: -7.1
      121:
        x: -13.53
        y: -7.4
      122:
        x: -13.53
        y: -8.15
      123:
        x: -14.0
        y: -8.15
      124:
        x: -10.0
        y: -7.85
      125:
        x: -8.63
        y: -8.15
      126:
        x: -8.63
        y: -8.6
      127:
        x: -8.63
        y: -8.9
      128:
        x: -7.65
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8275
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.98282
        y: 13.5
        z: 0.0
        h: -1.570796
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      start_delay: 0.1973
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6871
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 1.7281
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6608
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 1.4286
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9184
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      start_delay: 2.8542
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6917
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      start_delay: 2.1708
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7847
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      start_delay: 4.2231
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8409
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      start_delay: 2.5011
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.8113
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      start_delay: 3.7921
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.6633
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      start_delay: 3.0736
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.7821
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      start_delay: 3.5564
