hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_diverge_high_1128877429
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 0.0
        y: -7.85
      2:
        x: 1.17
        y: -8.15
      3:
        x: 1.17
        y: -8.6
      4:
        x: 1.17
        y: -8.9
      5:
        x: 2.15
        y: -10.6
      6:
        x: 14.1
        y: 10.71
      7:
        x: 14.4
        y: 10.71
      8:
        x: 15.0
        y: 10.71
      9:
        x: 15.0
        y: 10.65
      10:
        x: 15.0
        y: 9.8
      11:
        x: 15.0
        y: 8.0
      12:
        x: 15.0
        y: 6.4067
      13:
        x: 15.6
        y: 6.4067
      14:
        x: 15.9
        y: 6.4067
      15:
        x: 17.6
        y: 7.3
      16:
        x: -8.63
        y: -7.1
      17:
        x: -8.63
        y: -7.4
      18:
        x: -8.63
        y: -8.15
      19:
        x: -10.0
        y: -7.85
      20:
        x: -8.63
        y: -8.15
      21:
        x: -8.63
        y: -8.6
      22:
        x: -8.63
        y: -8.9
      23:
        x: -7.65
        y: -10.6
      24:
        x: 10.97
        y: -8.9
      25:
        x: 10.97
        y: -8.6
      26:
        x: 10.97
        y: -8.15
      27:
        x: 10.0
        y: -8.15
      28:
        x: 15.0
        y: -8.15
      29:
        x: 15.0
        y: -4.0
      30:
        x: 7.0
        y: -4.0
      31:
        x: 7.0
        y: -2.0
      32:
        x: 7.0
        y: 0.0
      33:
        x: 15.0
        y: 0.0
      34:
        x: 15.0
        y: 2.55
      35:
        x: 15.0
        y: 3.5
      36:
        x: 15.0
        y: 8.0
      37:
        x: 15.0
        y: 6.01
      38:
        x: 14.4
        y: 6.01
      39:
        x: 14.1
        y: 6.01
      40:
        x: 12.4
        y: 6.95
      41:
        x: -3.73
        y: -7.1
      42:
        x: -3.73
        y: -7.4
      43:
        x: -3.73
        y: -8.15
      44:
        x: -5.0
        y: -8.15
      45:
        x: -2.0
        y: -8.18
      46:
        x: 0.0
        y: -7.85
      47:
        x: 2.6
        y: -8.15
      48:
        x: 5.0
        y: -8.15
      49:
        x: 10.0
        y: -8.15
      50:
        x: 15.0
        y: -8.15
      51:
        x: 15.0
        y: -4.0
      52:
        x: 7.0
        y: -4.0
      53:
        x: 7.0
        y: -2.0
      54:
        x: 7.0
        y: 0.0
      55:
        x: 15.0
        y: 0.0
      56:
        x: 15.0
        y: 2.55
      57:
        x: 15.0
        y: 3.5
      58:
        x: 15.0
        y: 8.0
      59:
        x: 15.0
        y: 9.8
      60:
        x: 15.0
        y: 10.65
      61:
        x: 15.0
        y: 10.8733
      62:
        x: 15.6
        y: 10.8733
      63:
        x: 15.9
        y: 10.8733
      64:
        x: 17.6
        y: 11.7667
      65:
        x: 6.07
        y: -8.9
      66:
        x: 6.07
        y: -8.6
      67:
        x: 6.07
        y: -8.15
      68:
        x: 5.0
        y: -8.15
      69:
        x: 10.0
        y: -8.15
      70:
        x: 15.0
        y: -8.15
      71:
        x: 15.0
        y: -4.0
      72:
        x: 7.0
        y: -4.0
      73:
        x: 7.0
        y: -2.0
      74:
        x: 7.0
        y: 0.0
      75:
        x: 15.0
        y: 0.0
      76:
        x: 15.0
        y: 2.55
      77:
        x: 15.0
        y: 1.94
      78:
        x: 15.6
        y: 1.94
      79:
        x: 15.9
        y: 1.94
      80:
        x: 17.6
        y: 2.8333
      81:
        x: 15.9
        y: 10.8733
      82:
        x: 15.6
        y: 10.8733
      83:
        x: 15.0
        y: 10.8733
      84:
        x: 15.0
        y: 10.65
      85:
        x: 15.0
        y: 9.8
      86:
        x: 15.0
        y: 8.0
      87:
        x: 15.0
        y: 3.5
      88:
        x: 15.0
        y: 2.55
      89:
        x: 15.0
        y: 0.0
      90:
        x: 7.0
        y: 0.0
      91:
        x: 7.0
        y: -2.0
      92:
        x: 7.0
        y: -4.0
      93:
        x: 15.0
        y: -4.0
      94:
        x: 15.0
        y: -8.15
      95:
        x: 10.0
        y: -8.15
      96:
        x: 5.0
        y: -8.15
      97:
        x: 2.6
        y: -8.15
      98:
        x: 0.0
        y: -7.85
      99:
        x: -2.0
        y: -8.18
      100:
        x: -5.0
        y: -8.15
      101:
        x: -10.0
        y: -7.85
      102:
        x: -8.63
        y: -8.15
      103:
        x: -8.63
        y: -8.6
      104:
        x: -8.63
        y: -8.9
      105:
        x: -7.65
        y: -10.6
      106:
        x: -3.73
        y: -8.9
      107:
        x: -3.73
        y: -8.6
      108:
        x: -3.73
        y: -8.15
      109:
        x: -5.0
        y: -8.15
      110:
        x: -2.0
        y: -8.18
      111:
        x: 0.0
        y: -7.85
      112:
        x: 2.6
        y: -8.15
      113:
        x: 5.0
        y: -8.15
      114:
        x: 6.07
        y: -8.15
      115:
        x: 6.07
        y: -8.6
      116:
        x: 6.07
        y: -8.9
      117:
        x: 7.05
        y: -10.6
      118:
        x: -13.53
        y: -7.1
      119:
        x: -13.53
        y: -7.4
      120:
        x: -13.53
        y: -8.15
      121:
        x: -14.0
        y: -8.15
      122:
        x: -10.0
        y: -7.85
      123:
        x: -5.0
        y: -8.15
      124:
        x: -2.0
        y: -8.18
      125:
        x: 0.0
        y: -7.85
      126:
        x: 1.17
        y: -8.15
      127:
        x: 1.17
        y: -8.6
      128:
        x: 1.17
        y: -8.9
      129:
        x: 2.15
        y: -10.6
      130:
        x: -13.53
        y: -8.9
      131:
        x: -13.53
        y: -8.6
      132:
        x: -13.53
        y: -8.15
      133:
        x: -14.0
        y: -8.15
      134:
        x: -10.0
        y: -7.85
      135:
        x: -5.0
        y: -8.15
      136:
        x: -2.0
        y: -8.18
      137:
        x: 0.0
        y: -7.85
      138:
        x: 2.6
        y: -8.15
      139:
        x: 5.0
        y: -8.15
      140:
        x: 10.0
        y: -8.15
      141:
        x: 15.0
        y: -8.15
      142:
        x: 15.0
        y: -4.0
      143:
        x: 7.0
        y: -4.0
      144:
        x: 7.0
        y: -2.0
      145:
        x: 7.0
        y: 0.0
      146:
        x: 15.0
        y: 0.0
      147:
        x: 15.0
        y: 2.55
      148:
        x: 15.0
        y: 3.5
      149:
        x: 15.0
        y: 8.0
      150:
        x: 15.0
        y: 9.8
      151:
        x: 15.0
        y: 10.65
      152:
        x: 15.0
        y: 10.8733
      153:
        x: 15.6
        y: 10.8733
      154:
        x: 15.9
        y: 10.8733
      155:
        x: 17.6
        y: 11.7667
      156:
        x: 15.9
        y: 6.4067
      157:
        x: 15.6
        y: 6.4067
      158:
        x: 15.0
        y: 6.4067
      159:
        x: 15.0
        y: 8.0
      160:
        x: 15.0
        y: 3.5
      161:
        x: 15.0
        y: 2.55
      162:
        x: 15.0
        y: 0.0
      163:
        x: 7.0
        y: 0.0
      164:
        x: 7.0
        y: -2.0
      165:
        x: 7.0
        y: -4.0
      166:
        x: 15.0
        y: -4.0
      167:
        x: 15.0
        y: -8.15
      168:
        x: 10.0
        y: -8.15
      169:
        x: 5.0
        y: -8.15
      170:
        x: 2.6
        y: -8.15
      171:
        x: 0.0
        y: -7.85
      172:
        x: 1.17
        y: -8.15
      173:
        x: 1.17
        y: -7.4
      174:
        x: 1.17
        y: -7.1
      175:
        x: 2.15
        y: -5.4
      176:
        x: 14.1
        y: 6.01
      177:
        x: 14.4
        y: 6.01
      178:
        x: 15.0
        y: 6.01
      179:
        x: 15.0
        y: 8.0
      180:
        x: 15.0
        y: 3.5
      181:
        x: 15.0
        y: 2.55
      182:
        x: 15.0
        y: 0.0
      183:
        x: 7.0
        y: 0.0
      184:
        x: 7.0
        y: -2.0
      185:
        x: 7.0
        y: -4.0
      186:
        x: 15.0
        y: -4.0
      187:
        x: 15.0
        y: -8.15
      188:
        x: 10.0
        y: -8.15
      189:
        x: 5.0
        y: -8.15
      190:
        x: 2.6
        y: -8.15
      191:
        x: 0.0
        y: -7.85
      192:
        x: 1.17
        y: -8.15
      193:
        x: 1.17
        y: -7.4
      194:
        x: 1.17
        y: -7.1
      195:
        x: 2.15
        y: -5.4
      196:
        x: -8.63
        y: -8.9
      197:
        x: -8.63
        y: -8.6
      198:
        x: -8.63
        y: -8.15
      199:
        x: -10.0
        y: -7.85
      200:
        x: -8.63
        y: -8.15
      201:
        x: -8.63
        y: -7.4
      202:
        x: -8.63
        y: -7.1
      203:
        x: -7.65
        y: -5.4
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    - background_agent_11
    - background_agent_12
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.3288
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.0
        y: -8.18
        z: 0.0
        h: 0.163527
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 0.4965
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.5827
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      start_delay: 1.4471
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7664
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      start_delay: 1.0235
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7552
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      start_delay: 2.214
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.7594
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      start_delay: 1.7023
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7802
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      start_delay: 4.2624
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8462
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      start_delay: 4.4778
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.8149
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      start_delay: 3.6165
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.5992
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      start_delay: 2.1304
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.8245
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      - 146
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      - 154
      - 155
      start_delay: 1.9874
    background_agent_10:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.6881
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      - 165
      - 166
      - 167
      - 168
      - 169
      - 170
      - 171
      - 172
      - 173
      - 174
      - 175
      start_delay: 0.1322
    background_agent_11:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.5871
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 176
      - 177
      - 178
      - 179
      - 180
      - 181
      - 182
      - 183
      - 184
      - 185
      - 186
      - 187
      - 188
      - 189
      - 190
      - 191
      - 192
      - 193
      - 194
      - 195
      start_delay: 1.6735
    background_agent_12:
      id: 13
      group_id: -1
      skin: 0
      max_vel: 0.5991
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 196
      - 197
      - 198
      - 199
      - 200
      - 201
      - 202
      - 203
      start_delay: 0.8407
