hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_diverge_medium_1639024721
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -5.0
        y: -8.15
      2:
        x: -3.73
        y: -8.15
      3:
        x: -3.73
        y: -8.6
      4:
        x: -3.73
        y: -8.9
      5:
        x: -2.75
        y: -10.6
      6:
        x: -13.53
        y: -7.1
      7:
        x: -13.53
        y: -7.4
      8:
        x: -13.53
        y: -8.15
      9:
        x: -14.0
        y: -8.15
      10:
        x: -10.0
        y: -7.85
      11:
        x: -8.63
        y: -8.15
      12:
        x: -8.63
        y: -7.4
      13:
        x: -8.63
        y: -7.1
      14:
        x: -7.65
        y: -5.4
      15:
        x: 14.1
        y: 10.71
      16:
        x: 14.4
        y: 10.71
      17:
        x: 15.0
        y: 10.71
      18:
        x: 15.0
        y: 10.65
      19:
        x: 15.0
        y: 9.8
      20:
        x: 15.0
        y: 8.0
      21:
        x: 15.0
        y: 3.5
      22:
        x: 15.0
        y: 2.55
      23:
        x: 15.0
        y: 0.0
      24:
        x: 7.0
        y: 0.0
      25:
        x: 7.0
        y: -2.0
      26:
        x: 7.0
        y: -4.0
      27:
        x: 15.0
        y: -4.0
      28:
        x: 15.0
        y: -8.15
      29:
        x: 10.0
        y: -8.15
      30:
        x: 10.97
        y: -8.15
      31:
        x: 10.97
        y: -8.6
      32:
        x: 10.97
        y: -8.9
      33:
        x: 11.95
        y: -10.6
      34:
        x: 1.17
        y: -7.1
      35:
        x: 1.17
        y: -7.4
      36:
        x: 1.17
        y: -8.15
      37:
        x: 0.0
        y: -7.85
      38:
        x: 2.6
        y: -8.15
      39:
        x: 5.0
        y: -8.15
      40:
        x: 10.0
        y: -8.15
      41:
        x: 15.0
        y: -8.15
      42:
        x: 15.0
        y: -4.0
      43:
        x: 7.0
        y: -4.0
      44:
        x: 7.0
        y: -2.0
      45:
        x: 7.0
        y: 0.0
      46:
        x: 15.0
        y: 0.0
      47:
        x: 15.0
        y: 2.55
      48:
        x: 15.0
        y: 3.5
      49:
        x: 15.0
        y: 8.0
      50:
        x: 15.0
        y: 6.01
      51:
        x: 14.4
        y: 6.01
      52:
        x: 14.1
        y: 6.01
      53:
        x: 12.4
        y: 6.95
      54:
        x: -13.53
        y: -8.9
      55:
        x: -13.53
        y: -8.6
      56:
        x: -13.53
        y: -8.15
      57:
        x: -14.0
        y: -8.15
      58:
        x: -10.0
        y: -7.85
      59:
        x: -5.0
        y: -8.15
      60:
        x: -2.0
        y: -8.18
      61:
        x: 0.0
        y: -7.85
      62:
        x: 2.6
        y: -8.15
      63:
        x: 5.0
        y: -8.15
      64:
        x: 10.0
        y: -8.15
      65:
        x: 15.0
        y: -8.15
      66:
        x: 15.0
        y: -4.0
      67:
        x: 7.0
        y: -4.0
      68:
        x: 7.0
        y: -2.0
      69:
        x: 7.0
        y: 0.0
      70:
        x: 15.0
        y: 0.0
      71:
        x: 15.0
        y: 2.55
      72:
        x: 15.0
        y: 3.5
      73:
        x: 15.0
        y: 8.0
      74:
        x: 15.0
        y: 9.8
      75:
        x: 15.0
        y: 10.65
      76:
        x: 15.0
        y: 10.71
      77:
        x: 14.4
        y: 10.71
      78:
        x: 14.1
        y: 10.71
      79:
        x: 12.4
        y: 11.65
      80:
        x: 15.9
        y: 1.94
      81:
        x: 15.6
        y: 1.94
      82:
        x: 15.0
        y: 1.94
      83:
        x: 15.0
        y: 2.55
      84:
        x: 15.0
        y: 0.0
      85:
        x: 7.0
        y: 0.0
      86:
        x: 7.0
        y: -2.0
      87:
        x: 7.0
        y: -4.0
      88:
        x: 15.0
        y: -4.0
      89:
        x: 15.0
        y: -8.15
      90:
        x: 10.0
        y: -8.15
      91:
        x: 5.0
        y: -8.15
      92:
        x: 2.6
        y: -8.15
      93:
        x: 0.0
        y: -7.85
      94:
        x: 1.17
        y: -8.15
      95:
        x: 1.17
        y: -8.6
      96:
        x: 1.17
        y: -8.9
      97:
        x: 2.15
        y: -10.6
      98:
        x: 6.07
        y: -8.9
      99:
        x: 6.07
        y: -8.6
      100:
        x: 6.07
        y: -8.15
      101:
        x: 5.0
        y: -8.15
      102:
        x: 2.6
        y: -8.15
      103:
        x: 0.0
        y: -7.85
      104:
        x: -2.0
        y: -8.18
      105:
        x: -5.0
        y: -8.15
      106:
        x: -10.0
        y: -7.85
      107:
        x: -14.0
        y: -8.15
      108:
        x: -13.53
        y: -8.15
      109:
        x: -13.53
        y: -8.6
      110:
        x: -13.53
        y: -8.9
      111:
        x: -12.55
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.3686
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -10.0
        y: -7.85
        z: 0.0
        h: -0.059928
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 0.5409
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.5558
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      start_delay: 4.1189
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.5548
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      start_delay: 2.0846
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9192
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      start_delay: 2.4286
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.8403
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      start_delay: 4.8941
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.8302
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      start_delay: 2.1352
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8579
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      start_delay: 3.0883
