hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_conversation_group_high_1714028933
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 8.0
      2:
        x: 15.0
        y: 9.8
      3:
        x: 15.0
        y: 10.65
      4:
        x: 15.0
        y: 12.3
      5:
        x: 15.0
        y: 13.5
      6:
        x: 15.0
        y: 8.0
      7:
        x: 15.0
        y: 9.8
      8:
        x: 15.0
        y: 10.65
      9:
        x: 15.0
        y: 12.3
      10:
        x: 15.0
        y: 13.5
      11:
        x: 15.0
        y: 8.0
      12:
        x: 15.0
        y: 9.8
      13:
        x: 15.0
        y: 10.65
      14:
        x: 15.0
        y: 12.3
      15:
        x: 15.0
        y: 13.5
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 9.8
      18:
        x: 15.0
        y: 10.65
      19:
        x: 15.0
        y: 12.3
      20:
        x: 15.0
        y: 13.5
      21:
        x: 10.97
        y: -8.9
      22:
        x: 10.97
        y: -8.6
      23:
        x: 10.97
        y: -8.15
      24:
        x: 10.0
        y: -8.15
      25:
        x: 15.0
        y: -8.15
      26:
        x: 15.0
        y: -4.0
      27:
        x: 7.0
        y: -4.0
      28:
        x: 7.0
        y: -2.0
      29:
        x: 7.0
        y: 0.0
      30:
        x: 15.0
        y: 0.0
      31:
        x: 15.0
        y: 2.55
      32:
        x: 15.0
        y: 3.5
      33:
        x: 15.0
        y: 8.0
      34:
        x: 15.0
        y: 6.01
      35:
        x: 14.4
        y: 6.01
      36:
        x: 14.1
        y: 6.01
      37:
        x: 12.4
        y: 6.95
      38:
        x: 1.17
        y: -8.9
      39:
        x: 1.17
        y: -8.6
      40:
        x: 1.17
        y: -8.15
      41:
        x: 0.0
        y: -7.85
      42:
        x: 2.6
        y: -8.15
      43:
        x: 5.0
        y: -8.15
      44:
        x: 10.0
        y: -8.15
      45:
        x: 10.97
        y: -8.15
      46:
        x: 10.97
        y: -8.6
      47:
        x: 10.97
        y: -8.9
      48:
        x: 11.95
        y: -10.6
      49:
        x: -13.53
        y: -7.1
      50:
        x: -13.53
        y: -7.4
      51:
        x: -13.53
        y: -8.15
      52:
        x: -14.0
        y: -8.15
      53:
        x: -10.0
        y: -7.85
      54:
        x: -8.63
        y: -8.15
      55:
        x: -8.63
        y: -8.6
      56:
        x: -8.63
        y: -8.9
      57:
        x: -7.65
        y: -10.6
      58:
        x: 14.1
        y: 6.01
      59:
        x: 14.4
        y: 6.01
      60:
        x: 15.0
        y: 6.01
      61:
        x: 15.0
        y: 8.0
      62:
        x: 15.0
        y: 3.5
      63:
        x: 15.0
        y: 2.55
      64:
        x: 15.0
        y: 0.0
      65:
        x: 7.0
        y: 0.0
      66:
        x: 7.0
        y: -2.0
      67:
        x: 7.0
        y: -4.0
      68:
        x: 15.0
        y: -4.0
      69:
        x: 15.0
        y: -8.15
      70:
        x: 10.0
        y: -8.15
      71:
        x: 5.0
        y: -8.15
      72:
        x: 2.6
        y: -8.15
      73:
        x: 0.0
        y: -7.85
      74:
        x: 1.17
        y: -8.15
      75:
        x: 1.17
        y: -8.6
      76:
        x: 1.17
        y: -8.9
      77:
        x: 2.15
        y: -10.6
      78:
        x: 15.9
        y: 1.94
      79:
        x: 15.6
        y: 1.94
      80:
        x: 15.0
        y: 1.94
      81:
        x: 15.0
        y: 2.55
      82:
        x: 15.0
        y: 3.5
      83:
        x: 15.0
        y: 8.0
      84:
        x: 15.0
        y: 6.4067
      85:
        x: 15.6
        y: 6.4067
      86:
        x: 15.9
        y: 6.4067
      87:
        x: 17.6
        y: 7.3
      88:
        x: -8.63
        y: -7.1
      89:
        x: -8.63
        y: -7.4
      90:
        x: -8.63
        y: -8.15
      91:
        x: -10.0
        y: -7.85
      92:
        x: -5.0
        y: -8.15
      93:
        x: -2.0
        y: -8.18
      94:
        x: 0.0
        y: -7.85
      95:
        x: 2.6
        y: -8.15
      96:
        x: 5.0
        y: -8.15
      97:
        x: 10.0
        y: -8.15
      98:
        x: 10.97
        y: -8.15
      99:
        x: 10.97
        y: -8.6
      100:
        x: 10.97
        y: -8.9
      101:
        x: 11.95
        y: -10.6
      102:
        x: 15.9
        y: 10.8733
      103:
        x: 15.6
        y: 10.8733
      104:
        x: 15.0
        y: 10.8733
      105:
        x: 15.0
        y: 10.65
      106:
        x: 15.0
        y: 9.8
      107:
        x: 15.0
        y: 8.0
      108:
        x: 15.0
        y: 6.01
      109:
        x: 14.4
        y: 6.01
      110:
        x: 14.1
        y: 6.01
      111:
        x: 12.4
        y: 6.95
      112:
        x: 6.07
        y: -8.9
      113:
        x: 6.07
        y: -8.6
      114:
        x: 6.07
        y: -8.15
      115:
        x: 5.0
        y: -8.15
      116:
        x: 10.0
        y: -8.15
      117:
        x: 10.97
        y: -8.15
      118:
        x: 10.97
        y: -8.6
      119:
        x: 10.97
        y: -8.9
      120:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.5594
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.99836
        y: 5.52448
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 44.4806
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.623
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.99304
        y: 6.10816
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      start_delay: 35.592
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.6193
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.00271
        y: 6.69184
        z: 0.0
        h: 1.570796
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 11
      - 12
      - 13
      - 14
      - 15
      start_delay: 38.4326
    event_agent_4:
      id: 4
      group_id: 1
      skin: 3
      max_vel: 0.9419
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.98863
        y: 7.27552
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 36.1866
    background_agent_1:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.9617
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      start_delay: 3.8318
    background_agent_2:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.5759
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      start_delay: 4.4139
    background_agent_3:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.5788
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Surprised
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      start_delay: 0.7219
    background_agent_4:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.6758
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      start_delay: 3.2195
    background_agent_5:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.9583
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      start_delay: 4.7422
    background_agent_6:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.9685
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      start_delay: 0.7702
    background_agent_7:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.5639
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      start_delay: 4.5885
    background_agent_8:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.8924
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      start_delay: 1.4067
