hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_blind_corner_high_544906989
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: -4.0
      2:
        x: 7.0
        y: -4.0
      3:
        x: 1.17
        y: -8.9
      4:
        x: 1.17
        y: -8.6
      5:
        x: 1.17
        y: -8.15
      6:
        x: 0.0
        y: -7.85
      7:
        x: 2.6
        y: -8.15
      8:
        x: 5.0
        y: -8.15
      9:
        x: 10.0
        y: -8.15
      10:
        x: 15.0
        y: -8.15
      11:
        x: 15.0
        y: -4.0
      12:
        x: 7.0
        y: -4.0
      13:
        x: 7.0
        y: -2.0
      14:
        x: 7.0
        y: 0.0
      15:
        x: 15.0
        y: 0.0
      16:
        x: 15.0
        y: 2.55
      17:
        x: 15.0
        y: 1.94
      18:
        x: 15.6
        y: 1.94
      19:
        x: 15.9
        y: 1.94
      20:
        x: 17.6
        y: 2.8333
      21:
        x: 14.1
        y: 10.71
      22:
        x: 14.4
        y: 10.71
      23:
        x: 15.0
        y: 10.71
      24:
        x: 15.0
        y: 10.65
      25:
        x: 15.0
        y: 9.8
      26:
        x: 15.0
        y: 8.0
      27:
        x: 15.0
        y: 3.5
      28:
        x: 15.0
        y: 2.55
      29:
        x: 15.0
        y: 0.0
      30:
        x: 7.0
        y: 0.0
      31:
        x: 7.0
        y: -2.0
      32:
        x: 7.0
        y: -4.0
      33:
        x: 15.0
        y: -4.0
      34:
        x: 15.0
        y: -8.15
      35:
        x: 10.0
        y: -8.15
      36:
        x: 5.0
        y: -8.15
      37:
        x: 2.6
        y: -8.15
      38:
        x: 0.0
        y: -7.85
      39:
        x: -2.0
        y: -8.18
      40:
        x: -5.0
        y: -8.15
      41:
        x: -3.73
        y: -8.15
      42:
        x: -3.73
        y: -7.4
      43:
        x: -3.73
        y: -7.1
      44:
        x: -2.75
        y: -5.4
      45:
        x: -13.53
        y: -7.1
      46:
        x: -13.53
        y: -7.4
      47:
        x: -13.53
        y: -8.15
      48:
        x: -14.0
        y: -8.15
      49:
        x: -10.0
        y: -7.85
      50:
        x: -5.0
        y: -8.15
      51:
        x: -3.73
        y: -8.15
      52:
        x: -3.73
        y: -7.4
      53:
        x: -3.73
        y: -7.1
      54:
        x: -2.75
        y: -5.4
      55:
        x: -3.73
        y: -7.1
      56:
        x: -3.73
        y: -7.4
      57:
        x: -3.73
        y: -8.15
      58:
        x: -5.0
        y: -8.15
      59:
        x: -2.0
        y: -8.18
      60:
        x: 0.0
        y: -7.85
      61:
        x: 2.6
        y: -8.15
      62:
        x: 5.0
        y: -8.15
      63:
        x: 10.0
        y: -8.15
      64:
        x: 10.97
        y: -8.15
      65:
        x: 10.97
        y: -8.6
      66:
        x: 10.97
        y: -8.9
      67:
        x: 11.95
        y: -10.6
      68:
        x: -8.63
        y: -8.9
      69:
        x: -8.63
        y: -8.6
      70:
        x: -8.63
        y: -8.15
      71:
        x: -10.0
        y: -7.85
      72:
        x: -5.0
        y: -8.15
      73:
        x: -2.0
        y: -8.18
      74:
        x: 0.0
        y: -7.85
      75:
        x: 2.6
        y: -8.15
      76:
        x: 5.0
        y: -8.15
      77:
        x: 10.0
        y: -8.15
      78:
        x: 15.0
        y: -8.15
      79:
        x: 15.0
        y: -4.0
      80:
        x: 7.0
        y: -4.0
      81:
        x: 7.0
        y: -2.0
      82:
        x: 7.0
        y: 0.0
      83:
        x: 15.0
        y: 0.0
      84:
        x: 15.0
        y: 2.55
      85:
        x: 15.0
        y: 3.5
      86:
        x: 15.0
        y: 8.0
      87:
        x: 15.0
        y: 9.8
      88:
        x: 15.0
        y: 10.65
      89:
        x: 15.0
        y: 10.8733
      90:
        x: 15.6
        y: 10.8733
      91:
        x: 15.9
        y: 10.8733
      92:
        x: 17.6
        y: 11.7667
      93:
        x: 15.9
        y: 10.8733
      94:
        x: 15.6
        y: 10.8733
      95:
        x: 15.0
        y: 10.8733
      96:
        x: 15.0
        y: 10.65
      97:
        x: 15.0
        y: 9.8
      98:
        x: 15.0
        y: 8.0
      99:
        x: 15.0
        y: 3.5
      100:
        x: 15.0
        y: 2.55
      101:
        x: 15.0
        y: 0.0
      102:
        x: 7.0
        y: 0.0
      103:
        x: 7.0
        y: -2.0
      104:
        x: 7.0
        y: -4.0
      105:
        x: 15.0
        y: -4.0
      106:
        x: 15.0
        y: -8.15
      107:
        x: 10.0
        y: -8.15
      108:
        x: 5.0
        y: -8.15
      109:
        x: 2.6
        y: -8.15
      110:
        x: 0.0
        y: -7.85
      111:
        x: -2.0
        y: -8.18
      112:
        x: -5.0
        y: -8.15
      113:
        x: -10.0
        y: -7.85
      114:
        x: -14.0
        y: -8.15
      115:
        x: -13.53
        y: -8.15
      116:
        x: -13.53
        y: -8.6
      117:
        x: -13.53
        y: -8.9
      118:
        x: -12.55
        y: -10.6
      119:
        x: 6.07
        y: -8.9
      120:
        x: 6.07
        y: -8.6
      121:
        x: 6.07
        y: -8.15
      122:
        x: 5.0
        y: -8.15
      123:
        x: 2.6
        y: -8.15
      124:
        x: 0.0
        y: -7.85
      125:
        x: -2.0
        y: -8.18
      126:
        x: -5.0
        y: -8.15
      127:
        x: -10.0
        y: -7.85
      128:
        x: -8.63
        y: -8.15
      129:
        x: -8.63
        y: -7.4
      130:
        x: -8.63
        y: -7.1
      131:
        x: -7.65
        y: -5.4
      132:
        x: 14.1
        y: 6.01
      133:
        x: 14.4
        y: 6.01
      134:
        x: 15.0
        y: 6.01
      135:
        x: 15.0
        y: 8.0
      136:
        x: 15.0
        y: 3.5
      137:
        x: 15.0
        y: 2.55
      138:
        x: 15.0
        y: 0.0
      139:
        x: 7.0
        y: 0.0
      140:
        x: 7.0
        y: -2.0
      141:
        x: 7.0
        y: -4.0
      142:
        x: 15.0
        y: -4.0
      143:
        x: 15.0
        y: -8.15
      144:
        x: 10.0
        y: -8.15
      145:
        x: 5.0
        y: -8.15
      146:
        x: 2.6
        y: -8.15
      147:
        x: 0.0
        y: -7.85
      148:
        x: -2.0
        y: -8.18
      149:
        x: -5.0
        y: -8.15
      150:
        x: -3.73
        y: -8.15
      151:
        x: -3.73
        y: -7.4
      152:
        x: -3.73
        y: -7.1
      153:
        x: -2.75
        y: -5.4
      154:
        x: 15.9
        y: 6.4067
      155:
        x: 15.6
        y: 6.4067
      156:
        x: 15.0
        y: 6.4067
      157:
        x: 15.0
        y: 8.0
      158:
        x: 15.0
        y: 3.5
      159:
        x: 15.0
        y: 2.55
      160:
        x: 15.0
        y: 0.0
      161:
        x: 7.0
        y: 0.0
      162:
        x: 7.0
        y: -2.0
      163:
        x: 7.0
        y: -4.0
      164:
        x: 15.0
        y: -4.0
      165:
        x: 15.0
        y: -8.15
      166:
        x: 10.0
        y: -8.15
      167:
        x: 5.0
        y: -8.15
      168:
        x: 2.6
        y: -8.15
      169:
        x: 0.0
        y: -7.85
      170:
        x: -2.0
        y: -8.18
      171:
        x: -5.0
        y: -8.15
      172:
        x: -10.0
        y: -7.85
      173:
        x: -14.0
        y: -8.15
      174:
        x: -13.53
        y: -8.15
      175:
        x: -13.53
        y: -7.4
      176:
        x: -13.53
        y: -7.1
      177:
        x: -12.55
        y: -5.4
      178:
        x: -8.63
        y: -7.1
      179:
        x: -8.63
        y: -7.4
      180:
        x: -8.63
        y: -8.15
      181:
        x: -10.0
        y: -7.85
      182:
        x: -5.0
        y: -8.15
      183:
        x: -2.0
        y: -8.18
      184:
        x: 0.0
        y: -7.85
      185:
        x: 2.6
        y: -8.15
      186:
        x: 5.0
        y: -8.15
      187:
        x: 10.0
        y: -8.15
      188:
        x: 15.0
        y: -8.15
      189:
        x: 15.0
        y: -4.0
      190:
        x: 7.0
        y: -4.0
      191:
        x: 7.0
        y: -2.0
      192:
        x: 7.0
        y: 0.0
      193:
        x: 15.0
        y: 0.0
      194:
        x: 15.0
        y: 2.55
      195:
        x: 15.0
        y: 1.94
      196:
        x: 15.6
        y: 1.94
      197:
        x: 15.9
        y: 1.94
      198:
        x: 17.6
        y: 2.8333
      199:
        x: -13.53
        y: -8.9
      200:
        x: -13.53
        y: -8.6
      201:
        x: -13.53
        y: -8.15
      202:
        x: -14.0
        y: -8.15
      203:
        x: -10.0
        y: -7.85
      204:
        x: -5.0
        y: -8.15
      205:
        x: -2.0
        y: -8.18
      206:
        x: 0.0
        y: -7.85
      207:
        x: 2.6
        y: -8.15
      208:
        x: 5.0
        y: -8.15
      209:
        x: 10.0
        y: -8.15
      210:
        x: 15.0
        y: -8.15
      211:
        x: 15.0
        y: -4.0
      212:
        x: 7.0
        y: -4.0
      213:
        x: 7.0
        y: -2.0
      214:
        x: 7.0
        y: 0.0
      215:
        x: 15.0
        y: 0.0
      216:
        x: 15.0
        y: 2.55
      217:
        x: 15.0
        y: 3.5
      218:
        x: 15.0
        y: 8.0
      219:
        x: 15.0
        y: 6.01
      220:
        x: 14.4
        y: 6.01
      221:
        x: 14.1
        y: 6.01
      222:
        x: 12.4
        y: 6.95
      223:
        x: 15.9
        y: 1.94
      224:
        x: 15.6
        y: 1.94
      225:
        x: 15.0
        y: 1.94
      226:
        x: 15.0
        y: 2.55
      227:
        x: 15.0
        y: 0.0
      228:
        x: 7.0
        y: 0.0
      229:
        x: 7.0
        y: -2.0
      230:
        x: 7.0
        y: -4.0
      231:
        x: 15.0
        y: -4.0
      232:
        x: 15.0
        y: -8.15
      233:
        x: 10.0
        y: -8.15
      234:
        x: 10.97
        y: -8.15
      235:
        x: 10.97
        y: -8.6
      236:
        x: 10.97
        y: -8.9
      237:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    - background_agent_11
    - background_agent_12
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.7433
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.0
        y: -8.15
        z: 0.0
        h: 1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 9.2882
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.7839
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 2.8593
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7929
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      start_delay: 2.0437
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.8709
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      start_delay: 2.5239
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.8758
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      start_delay: 2.2686
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7051
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      start_delay: 3.3585
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.675
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      start_delay: 1.5593
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.8676
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      start_delay: 1.9228
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.9811
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      - 146
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      start_delay: 0.3146
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.8361
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 154
      - 155
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      - 165
      - 166
      - 167
      - 168
      - 169
      - 170
      - 171
      - 172
      - 173
      - 174
      - 175
      - 176
      - 177
      start_delay: 4.2127
    background_agent_10:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.9355
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 178
      - 179
      - 180
      - 181
      - 182
      - 183
      - 184
      - 185
      - 186
      - 187
      - 188
      - 189
      - 190
      - 191
      - 192
      - 193
      - 194
      - 195
      - 196
      - 197
      - 198
      start_delay: 2.3289
    background_agent_11:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.6051
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 199
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 209
      - 210
      - 211
      - 212
      - 213
      - 214
      - 215
      - 216
      - 217
      - 218
      - 219
      - 220
      - 221
      - 222
      start_delay: 3.9857
    background_agent_12:
      id: 13
      group_id: -1
      skin: 0
      max_vel: 0.8511
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 223
      - 224
      - 225
      - 226
      - 227
      - 228
      - 229
      - 230
      - 231
      - 232
      - 233
      - 234
      - 235
      - 236
      - 237
      start_delay: 1.9975
