hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_merge_medium_43006
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 1.17
        y: -7.1
      2:
        x: 1.17
        y: -7.4
      3:
        x: 1.17
        y: -8.15
      4:
        x: 0.0
        y: -7.85
      5:
        x: 2.6
        y: -8.15
      6:
        x: 5.0
        y: -8.15
      7:
        x: -13.53
        y: -7.1
      8:
        x: -13.53
        y: -7.4
      9:
        x: -13.53
        y: -8.15
      10:
        x: -14.0
        y: -8.15
      11:
        x: -10.0
        y: -7.85
      12:
        x: -5.0
        y: -8.15
      13:
        x: -2.0
        y: -8.18
      14:
        x: 0.0
        y: -7.85
      15:
        x: 2.6
        y: -8.15
      16:
        x: 5.0
        y: -8.15
      17:
        x: 10.0
        y: -8.15
      18:
        x: 10.97
        y: -8.15
      19:
        x: 10.97
        y: -8.6
      20:
        x: 10.97
        y: -8.9
      21:
        x: 11.95
        y: -10.6
      22:
        x: -8.63
        y: -7.1
      23:
        x: -8.63
        y: -7.4
      24:
        x: -8.63
        y: -8.15
      25:
        x: -10.0
        y: -7.85
      26:
        x: -8.63
        y: -8.15
      27:
        x: -8.63
        y: -8.6
      28:
        x: -8.63
        y: -8.9
      29:
        x: -7.65
        y: -10.6
      30:
        x: 14.1
        y: 6.01
      31:
        x: 14.4
        y: 6.01
      32:
        x: 15.0
        y: 6.01
      33:
        x: 15.0
        y: 8.0
      34:
        x: 15.0
        y: 3.5
      35:
        x: 15.0
        y: 2.55
      36:
        x: 15.0
        y: 0.0
      37:
        x: 7.0
        y: 0.0
      38:
        x: 7.0
        y: -2.0
      39:
        x: 7.0
        y: -4.0
      40:
        x: 15.0
        y: -4.0
      41:
        x: 15.0
        y: -8.15
      42:
        x: 10.0
        y: -8.15
      43:
        x: 5.0
        y: -8.15
      44:
        x: 2.6
        y: -8.15
      45:
        x: 0.0
        y: -7.85
      46:
        x: -2.0
        y: -8.18
      47:
        x: -5.0
        y: -8.15
      48:
        x: -3.73
        y: -8.15
      49:
        x: -3.73
        y: -8.6
      50:
        x: -3.73
        y: -8.9
      51:
        x: -2.75
        y: -10.6
      52:
        x: -3.73
        y: -7.1
      53:
        x: -3.73
        y: -7.4
      54:
        x: -3.73
        y: -8.15
      55:
        x: -5.0
        y: -8.15
      56:
        x: -10.0
        y: -7.85
      57:
        x: -14.0
        y: -8.15
      58:
        x: -13.53
        y: -8.15
      59:
        x: -13.53
        y: -7.4
      60:
        x: -13.53
        y: -7.1
      61:
        x: -12.55
        y: -5.4
      62:
        x: -13.53
        y: -8.9
      63:
        x: -13.53
        y: -8.6
      64:
        x: -13.53
        y: -8.15
      65:
        x: -14.0
        y: -8.15
      66:
        x: -10.0
        y: -7.85
      67:
        x: -5.0
        y: -8.15
      68:
        x: -2.0
        y: -8.18
      69:
        x: 0.0
        y: -7.85
      70:
        x: 1.17
        y: -8.15
      71:
        x: 1.17
        y: -8.6
      72:
        x: 1.17
        y: -8.9
      73:
        x: 2.15
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8091
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      start_delay: 3.8248
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6073
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      start_delay: 4.4714
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.8467
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      start_delay: 2.6968
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.6309
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      start_delay: 0.2672
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6486
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      start_delay: 2.4987
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.709
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      start_delay: 4.1044
