hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_enter_room_high_240506195
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 0.0
        y: -7.85
      2:
        x: 1.17
        y: -8.15
      3:
        x: 1.17
        y: -7.4
      4:
        x: 1.17
        y: -7.1
      5:
        x: 2.15
        y: -5.4
      6:
        x: -8.63
        y: -8.9
      7:
        x: -8.63
        y: -8.6
      8:
        x: -8.63
        y: -8.15
      9:
        x: -10.0
        y: -7.85
      10:
        x: -5.0
        y: -8.15
      11:
        x: -2.0
        y: -8.18
      12:
        x: 0.0
        y: -7.85
      13:
        x: 2.6
        y: -8.15
      14:
        x: 5.0
        y: -8.15
      15:
        x: 10.0
        y: -8.15
      16:
        x: 15.0
        y: -8.15
      17:
        x: 15.0
        y: -4.0
      18:
        x: 7.0
        y: -4.0
      19:
        x: 7.0
        y: -2.0
      20:
        x: 7.0
        y: 0.0
      21:
        x: 15.0
        y: 0.0
      22:
        x: 15.0
        y: 2.55
      23:
        x: 15.0
        y: 3.5
      24:
        x: 15.0
        y: 8.0
      25:
        x: 15.0
        y: 9.8
      26:
        x: 15.0
        y: 10.65
      27:
        x: 15.0
        y: 10.71
      28:
        x: 14.4
        y: 10.71
      29:
        x: 14.1
        y: 10.71
      30:
        x: 12.4
        y: 11.65
      31:
        x: -13.53
        y: -7.1
      32:
        x: -13.53
        y: -7.4
      33:
        x: -13.53
        y: -8.15
      34:
        x: -14.0
        y: -8.15
      35:
        x: -10.0
        y: -7.85
      36:
        x: -5.0
        y: -8.15
      37:
        x: -2.0
        y: -8.18
      38:
        x: 0.0
        y: -7.85
      39:
        x: 2.6
        y: -8.15
      40:
        x: 5.0
        y: -8.15
      41:
        x: 10.0
        y: -8.15
      42:
        x: 15.0
        y: -8.15
      43:
        x: 15.0
        y: -4.0
      44:
        x: 7.0
        y: -4.0
      45:
        x: 7.0
        y: -2.0
      46:
        x: 7.0
        y: 0.0
      47:
        x: 15.0
        y: 0.0
      48:
        x: 15.0
        y: 2.55
      49:
        x: 15.0
        y: 3.5
      50:
        x: 15.0
        y: 8.0
      51:
        x: 15.0
        y: 6.4067
      52:
        x: 15.6
        y: 6.4067
      53:
        x: 15.9
        y: 6.4067
      54:
        x: 17.6
        y: 7.3
      55:
        x: 6.07
        y: -8.9
      56:
        x: 6.07
        y: -8.6
      57:
        x: 6.07
        y: -8.15
      58:
        x: 5.0
        y: -8.15
      59:
        x: 10.0
        y: -8.15
      60:
        x: 15.0
        y: -8.15
      61:
        x: 15.0
        y: -4.0
      62:
        x: 7.0
        y: -4.0
      63:
        x: 7.0
        y: -2.0
      64:
        x: 7.0
        y: 0.0
      65:
        x: 15.0
        y: 0.0
      66:
        x: 15.0
        y: 2.55
      67:
        x: 15.0
        y: 3.5
      68:
        x: 15.0
        y: 8.0
      69:
        x: 15.0
        y: 6.01
      70:
        x: 14.4
        y: 6.01
      71:
        x: 14.1
        y: 6.01
      72:
        x: 12.4
        y: 6.95
      73:
        x: 15.9
        y: 6.4067
      74:
        x: 15.6
        y: 6.4067
      75:
        x: 15.0
        y: 6.4067
      76:
        x: 15.0
        y: 8.0
      77:
        x: 15.0
        y: 6.01
      78:
        x: 14.4
        y: 6.01
      79:
        x: 14.1
        y: 6.01
      80:
        x: 12.4
        y: 6.95
      81:
        x: 14.1
        y: 10.71
      82:
        x: 14.4
        y: 10.71
      83:
        x: 15.0
        y: 10.71
      84:
        x: 15.0
        y: 10.65
      85:
        x: 15.0
        y: 9.8
      86:
        x: 15.0
        y: 8.0
      87:
        x: 15.0
        y: 3.5
      88:
        x: 15.0
        y: 2.55
      89:
        x: 15.0
        y: 0.0
      90:
        x: 7.0
        y: 0.0
      91:
        x: 7.0
        y: -2.0
      92:
        x: 7.0
        y: -4.0
      93:
        x: 15.0
        y: -4.0
      94:
        x: 15.0
        y: -8.15
      95:
        x: 10.0
        y: -8.15
      96:
        x: 5.0
        y: -8.15
      97:
        x: 6.07
        y: -8.15
      98:
        x: 6.07
        y: -8.6
      99:
        x: 6.07
        y: -8.9
      100:
        x: 7.05
        y: -10.6
      101:
        x: 1.17
        y: -7.1
      102:
        x: 1.17
        y: -7.4
      103:
        x: 1.17
        y: -8.15
      104:
        x: 0.0
        y: -7.85
      105:
        x: -2.0
        y: -8.18
      106:
        x: -5.0
        y: -8.15
      107:
        x: -3.73
        y: -8.15
      108:
        x: -3.73
        y: -7.4
      109:
        x: -3.73
        y: -7.1
      110:
        x: -2.75
        y: -5.4
      111:
        x: -13.53
        y: -8.9
      112:
        x: -13.53
        y: -8.6
      113:
        x: -13.53
        y: -8.15
      114:
        x: -14.0
        y: -8.15
      115:
        x: -10.0
        y: -7.85
      116:
        x: -5.0
        y: -8.15
      117:
        x: -2.0
        y: -8.18
      118:
        x: 0.0
        y: -7.85
      119:
        x: 2.6
        y: -8.15
      120:
        x: 5.0
        y: -8.15
      121:
        x: 10.0
        y: -8.15
      122:
        x: 15.0
        y: -8.15
      123:
        x: 15.0
        y: -4.0
      124:
        x: 7.0
        y: -4.0
      125:
        x: 7.0
        y: -2.0
      126:
        x: 7.0
        y: 0.0
      127:
        x: 15.0
        y: 0.0
      128:
        x: 15.0
        y: 2.55
      129:
        x: 15.0
        y: 3.5
      130:
        x: 15.0
        y: 8.0
      131:
        x: 15.0
        y: 9.8
      132:
        x: 15.0
        y: 10.65
      133:
        x: 15.0
        y: 10.8733
      134:
        x: 15.6
        y: 10.8733
      135:
        x: 15.9
        y: 10.8733
      136:
        x: 17.6
        y: 11.7667
      137:
        x: -3.73
        y: -7.1
      138:
        x: -3.73
        y: -7.4
      139:
        x: -3.73
        y: -8.15
      140:
        x: -5.0
        y: -8.15
      141:
        x: -2.0
        y: -8.18
      142:
        x: 0.0
        y: -7.85
      143:
        x: 1.17
        y: -8.15
      144:
        x: 1.17
        y: -7.4
      145:
        x: 1.17
        y: -7.1
      146:
        x: 2.15
        y: -5.4
      147:
        x: 15.9
        y: 10.8733
      148:
        x: 15.6
        y: 10.8733
      149:
        x: 15.0
        y: 10.8733
      150:
        x: 15.0
        y: 10.65
      151:
        x: 15.0
        y: 9.8
      152:
        x: 15.0
        y: 8.0
      153:
        x: 15.0
        y: 3.5
      154:
        x: 15.0
        y: 2.55
      155:
        x: 15.0
        y: 0.0
      156:
        x: 7.0
        y: 0.0
      157:
        x: 7.0
        y: -2.0
      158:
        x: 7.0
        y: -4.0
      159:
        x: 15.0
        y: -4.0
      160:
        x: 15.0
        y: -8.15
      161:
        x: 10.0
        y: -8.15
      162:
        x: 5.0
        y: -8.15
      163:
        x: 2.6
        y: -8.15
      164:
        x: 0.0
        y: -7.85
      165:
        x: -2.0
        y: -8.18
      166:
        x: -5.0
        y: -8.15
      167:
        x: -10.0
        y: -7.85
      168:
        x: -8.63
        y: -8.15
      169:
        x: -8.63
        y: -8.6
      170:
        x: -8.63
        y: -8.9
      171:
        x: -7.65
        y: -10.6
      172:
        x: 1.17
        y: -8.9
      173:
        x: 1.17
        y: -8.6
      174:
        x: 1.17
        y: -8.15
      175:
        x: 0.0
        y: -7.85
      176:
        x: -2.0
        y: -8.18
      177:
        x: -5.0
        y: -8.15
      178:
        x: -10.0
        y: -7.85
      179:
        x: -14.0
        y: -8.15
      180:
        x: -13.53
        y: -8.15
      181:
        x: -13.53
        y: -7.4
      182:
        x: -13.53
        y: -7.1
      183:
        x: -12.55
        y: -5.4
      184:
        x: -8.63
        y: -7.1
      185:
        x: -8.63
        y: -7.4
      186:
        x: -8.63
        y: -8.15
      187:
        x: -10.0
        y: -7.85
      188:
        x: -14.0
        y: -8.15
      189:
        x: -13.53
        y: -8.15
      190:
        x: -13.53
        y: -8.6
      191:
        x: -13.53
        y: -8.9
      192:
        x: -12.55
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    - background_agent_11
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.6748
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.6
        y: -8.15
        z: 0.0
        h: 3.026716
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 5.3317
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9908
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 1.9157
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.5599
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      start_delay: 0.2197
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7733
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      start_delay: 1.2014
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6903
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      start_delay: 3.8824
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.7578
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      start_delay: 0.8412
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.5984
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      start_delay: 3.2112
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.7884
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      start_delay: 0.2484
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.8174
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      - 144
      - 145
      - 146
      start_delay: 2.0796
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.7648
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      - 154
      - 155
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      - 165
      - 166
      - 167
      - 168
      - 169
      - 170
      - 171
      start_delay: 0.9953
    background_agent_10:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.6101
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 172
      - 173
      - 174
      - 175
      - 176
      - 177
      - 178
      - 179
      - 180
      - 181
      - 182
      - 183
      start_delay: 1.5459
    background_agent_11:
      id: 12
      group_id: -1
      skin: 3
      max_vel: 0.8936
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 184
      - 185
      - 186
      - 187
      - 188
      - 189
      - 190
      - 191
      - 192
      start_delay: 0.5565
