hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_robot_overtake_medium_789498502
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 0.0
        y: -7.85
      2:
        x: 2.6
        y: -8.15
      3:
        x: 5.0
        y: -8.15
      4:
        x: 10.0
        y: -8.15
      5:
        x: 6.07
        y: -8.9
      6:
        x: 6.07
        y: -8.6
      7:
        x: 6.07
        y: -8.15
      8:
        x: 5.0
        y: -8.15
      9:
        x: 2.6
        y: -8.15
      10:
        x: 0.0
        y: -7.85
      11:
        x: -2.0
        y: -8.18
      12:
        x: -5.0
        y: -8.15
      13:
        x: -10.0
        y: -7.85
      14:
        x: -14.0
        y: -8.15
      15:
        x: -13.53
        y: -8.15
      16:
        x: -13.53
        y: -8.6
      17:
        x: -13.53
        y: -8.9
      18:
        x: -12.55
        y: -10.6
      19:
        x: 14.1
        y: 6.01
      20:
        x: 14.4
        y: 6.01
      21:
        x: 15.0
        y: 6.01
      22:
        x: 15.0
        y: 8.0
      23:
        x: 15.0
        y: 3.5
      24:
        x: 15.0
        y: 2.55
      25:
        x: 15.0
        y: 0.0
      26:
        x: 7.0
        y: 0.0
      27:
        x: 7.0
        y: -2.0
      28:
        x: 7.0
        y: -4.0
      29:
        x: 15.0
        y: -4.0
      30:
        x: 15.0
        y: -8.15
      31:
        x: 10.0
        y: -8.15
      32:
        x: 5.0
        y: -8.15
      33:
        x: 2.6
        y: -8.15
      34:
        x: 0.0
        y: -7.85
      35:
        x: -2.0
        y: -8.18
      36:
        x: -5.0
        y: -8.15
      37:
        x: -10.0
        y: -7.85
      38:
        x: -14.0
        y: -8.15
      39:
        x: -13.53
        y: -8.15
      40:
        x: -13.53
        y: -7.4
      41:
        x: -13.53
        y: -7.1
      42:
        x: -12.55
        y: -5.4
      43:
        x: 1.17
        y: -8.9
      44:
        x: 1.17
        y: -8.6
      45:
        x: 1.17
        y: -8.15
      46:
        x: 0.0
        y: -7.85
      47:
        x: 2.6
        y: -8.15
      48:
        x: 5.0
        y: -8.15
      49:
        x: 10.0
        y: -8.15
      50:
        x: 15.0
        y: -8.15
      51:
        x: 15.0
        y: -4.0
      52:
        x: 7.0
        y: -4.0
      53:
        x: 7.0
        y: -2.0
      54:
        x: 7.0
        y: 0.0
      55:
        x: 15.0
        y: 0.0
      56:
        x: 15.0
        y: 2.55
      57:
        x: 15.0
        y: 1.94
      58:
        x: 15.6
        y: 1.94
      59:
        x: 15.9
        y: 1.94
      60:
        x: 17.6
        y: 2.8333
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.2844
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -1.9951
        y: -8.2097
        z: 0.0
        h: 0.163527
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 0.3383
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.985
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      start_delay: 4.9883
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6953
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      start_delay: 3.4567
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.8614
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      start_delay: 0.8158
