hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_multi_crossing_medium_2109744838
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -8.9
      2:
        x: -8.63
        y: -8.6
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -8.63
        y: -8.15
      6:
        x: -8.63
        y: -7.4
      7:
        x: -8.63
        y: -7.1
      8:
        x: -7.65
        y: -5.4
      9:
        x: -3.73
        y: -7.1
      10:
        x: -3.73
        y: -7.4
      11:
        x: -3.73
        y: -8.15
      12:
        x: -5.0
        y: -8.15
      13:
        x: -3.73
        y: -8.15
      14:
        x: -3.73
        y: -8.6
      15:
        x: -3.73
        y: -8.9
      16:
        x: -2.75
        y: -10.6
      17:
        x: 1.17
        y: -8.9
      18:
        x: 1.17
        y: -8.6
      19:
        x: 1.17
        y: -8.15
      20:
        x: 0.0
        y: -7.85
      21:
        x: 1.17
        y: -8.15
      22:
        x: 1.17
        y: -7.4
      23:
        x: 1.17
        y: -7.1
      24:
        x: 2.15
        y: -5.4
      25:
        x: 14.1
        y: 10.71
      26:
        x: 14.4
        y: 10.71
      27:
        x: 15.0
        y: 10.71
      28:
        x: 15.0
        y: 10.65
      29:
        x: 15.0
        y: 9.8
      30:
        x: 15.0
        y: 8.0
      31:
        x: 15.0
        y: 6.01
      32:
        x: 14.4
        y: 6.01
      33:
        x: 14.1
        y: 6.01
      34:
        x: 12.4
        y: 6.95
      35:
        x: 15.9
        y: 10.8733
      36:
        x: 15.6
        y: 10.8733
      37:
        x: 15.0
        y: 10.8733
      38:
        x: 15.0
        y: 10.65
      39:
        x: 15.0
        y: 9.8
      40:
        x: 15.0
        y: 8.0
      41:
        x: 15.0
        y: 3.5
      42:
        x: 15.0
        y: 2.55
      43:
        x: 15.0
        y: 0.0
      44:
        x: 7.0
        y: 0.0
      45:
        x: 7.0
        y: -2.0
      46:
        x: 7.0
        y: -4.0
      47:
        x: 15.0
        y: -4.0
      48:
        x: 15.0
        y: -8.15
      49:
        x: 10.0
        y: -8.15
      50:
        x: 5.0
        y: -8.15
      51:
        x: 2.6
        y: -8.15
      52:
        x: 0.0
        y: -7.85
      53:
        x: 1.17
        y: -8.15
      54:
        x: 1.17
        y: -8.6
      55:
        x: 1.17
        y: -8.9
      56:
        x: 2.15
        y: -10.6
      57:
        x: -8.63
        y: -7.1
      58:
        x: -8.63
        y: -7.4
      59:
        x: -8.63
        y: -8.15
      60:
        x: -10.0
        y: -7.85
      61:
        x: -5.0
        y: -8.15
      62:
        x: -2.0
        y: -8.18
      63:
        x: 0.0
        y: -7.85
      64:
        x: 2.6
        y: -8.15
      65:
        x: 5.0
        y: -8.15
      66:
        x: 10.0
        y: -8.15
      67:
        x: 15.0
        y: -8.15
      68:
        x: 15.0
        y: -4.0
      69:
        x: 7.0
        y: -4.0
      70:
        x: 7.0
        y: -2.0
      71:
        x: 7.0
        y: 0.0
      72:
        x: 15.0
        y: 0.0
      73:
        x: 15.0
        y: 2.55
      74:
        x: 15.0
        y: 1.94
      75:
        x: 15.6
        y: 1.94
      76:
        x: 15.9
        y: 1.94
      77:
        x: 17.6
        y: 2.8333
      78:
        x: -3.73
        y: -8.9
      79:
        x: -3.73
        y: -8.6
      80:
        x: -3.73
        y: -8.15
      81:
        x: -5.0
        y: -8.15
      82:
        x: -2.0
        y: -8.18
      83:
        x: 0.0
        y: -7.85
      84:
        x: 2.6
        y: -8.15
      85:
        x: 5.0
        y: -8.15
      86:
        x: 10.0
        y: -8.15
      87:
        x: 10.97
        y: -8.15
      88:
        x: 10.97
        y: -8.6
      89:
        x: 10.97
        y: -8.9
      90:
        x: 11.95
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.6955
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 1.175
    event_agent_2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.842
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      start_delay: 11.1077
    event_agent_3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.9332
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      start_delay: 21.2007
    background_agent_1:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9175
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      start_delay: 0.9575
    background_agent_2:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.6064
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      start_delay: 2.3052
    background_agent_3:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.9551
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      start_delay: 2.9735
    background_agent_4:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.5594
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      start_delay: 3.2798
