hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_sudden_entry_low_1077571669
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -7.4
      2:
        x: -8.63
        y: -8.15
      3:
        x: -10.0
        y: -7.85
      4:
        x: -5.0
        y: -8.15
      5:
        x: 15.9
        y: 6.4067
      6:
        x: 15.6
        y: 6.4067
      7:
        x: 15.0
        y: 6.4067
      8:
        x: 15.0
        y: 8.0
      9:
        x: 15.0
        y: 3.5
      10:
        x: 15.0
        y: 2.55
      11:
        x: 15.0
        y: 0.0
      12:
        x: 7.0
        y: 0.0
      13:
        x: 7.0
        y: -2.0
      14:
        x: 7.0
        y: -4.0
      15:
        x: 15.0
        y: -4.0
      16:
        x: 15.0
        y: -8.15
      17:
        x: 10.0
        y: -8.15
      18:
        x: 5.0
        y: -8.15
      19:
        x: 2.6
        y: -8.15
      20:
        x: 0.0
        y: -7.85
      21:
        x: -2.0
        y: -8.18
      22:
        x: -5.0
        y: -8.15
      23:
        x: -10.0
        y: -7.85
      24:
        x: -14.0
        y: -8.15
      25:
        x: -13.53
        y: -8.15
      26:
        x: -13.53
        y: -7.4
      27:
        x: -13.53
        y: -7.1
      28:
        x: -12.55
        y: -5.4
    agents:
    - event_agent_1
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.906
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -8.63
        y: -7.1
        z: 0.0
        h: -1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 4.5075
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9127
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      start_delay: 4.3461
