hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_waiting_person_low_873280711
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.6
        y: 10.8733
      2:
        x: 15.0
        y: 10.8733
      3:
        x: 15.0
        y: 10.65
      4:
        x: 15.0
        y: 12.3
      5:
        x: 1.17
        y: -8.9
      6:
        x: 1.17
        y: -8.6
      7:
        x: 1.17
        y: -8.15
      8:
        x: 0.0
        y: -7.85
      9:
        x: -2.0
        y: -8.18
      10:
        x: -5.0
        y: -8.15
      11:
        x: -3.73
        y: -8.15
      12:
        x: -3.73
        y: -7.4
      13:
        x: -3.73
        y: -7.1
      14:
        x: -2.75
        y: -5.4
    agents:
    - event_agent_1
    - background_agent_1
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.9346
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 15.9
        y: 10.8733
        z: 0.0
        h: 3.141593
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      start_delay: 8.9896
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.8589
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      start_delay: 1.8423
