hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_narrow_passing_medium_286131692
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -14.0
        y: -8.15
      3:
        x: 6.07
        y: -8.9
      4:
        x: 6.07
        y: -8.6
      5:
        x: 6.07
        y: -8.15
      6:
        x: 5.0
        y: -8.15
      7:
        x: 10.0
        y: -8.15
      8:
        x: 15.0
        y: -8.15
      9:
        x: 15.0
        y: -4.0
      10:
        x: 7.0
        y: -4.0
      11:
        x: 7.0
        y: -2.0
      12:
        x: 7.0
        y: 0.0
      13:
        x: 15.0
        y: 0.0
      14:
        x: 15.0
        y: 2.55
      15:
        x: 15.0
        y: 3.5
      16:
        x: 15.0
        y: 8.0
      17:
        x: 15.0
        y: 6.01
      18:
        x: 14.4
        y: 6.01
      19:
        x: 14.1
        y: 6.01
      20:
        x: 12.4
        y: 6.95
      21:
        x: 14.1
        y: 6.01
      22:
        x: 14.4
        y: 6.01
      23:
        x: 15.0
        y: 6.01
      24:
        x: 15.0
        y: 8.0
      25:
        x: 15.0
        y: 9.8
      26:
        x: 15.0
        y: 10.65
      27:
        x: 15.0
        y: 10.8733
      28:
        x: 15.6
        y: 10.8733
      29:
        x: 15.9
        y: 10.8733
      30:
        x: 17.6
        y: 11.7667
      31:
        x: 15.9
        y: 1.94
      32:
        x: 15.6
        y: 1.94
      33:
        x: 15.0
        y: 1.94
      34:
        x: 15.0
        y: 2.55
      35:
        x: 15.0
        y: 0.0
      36:
        x: 7.0
        y: 0.0
      37:
        x: 7.0
        y: -2.0
      38:
        x: 7.0
        y: -4.0
      39:
        x: 15.0
        y: -4.0
      40:
        x: 15.0
        y: -8.15
      41:
        x: 10.0
        y: -8.15
      42:
        x: 5.0
        y: -8.15
      43:
        x: 2.6
        y: -8.15
      44:
        x: 0.0
        y: -7.85
      45:
        x: -2.0
        y: -8.18
      46:
        x: -5.0
        y: -8.15
      47:
        x: -10.0
        y: -7.85
      48:
        x: -14.0
        y: -8.15
      49:
        x: -13.53
        y: -8.15
      50:
        x: -13.53
        y: -8.6
      51:
        x: -13.53
        y: -8.9
      52:
        x: -12.55
        y: -10.6
      53:
        x: 15.9
        y: 6.4067
      54:
        x: 15.6
        y: 6.4067
      55:
        x: 15.0
        y: 6.4067
      56:
        x: 15.0
        y: 8.0
      57:
        x: 15.0
        y: 3.5
      58:
        x: 15.0
        y: 2.55
      59:
        x: 15.0
        y: 0.0
      60:
        x: 7.0
        y: 0.0
      61:
        x: 7.0
        y: -2.0
      62:
        x: 7.0
        y: -4.0
      63:
        x: 15.0
        y: -4.0
      64:
        x: 15.0
        y: -8.15
      65:
        x: 10.0
        y: -8.15
      66:
        x: 5.0
        y: -8.15
      67:
        x: 2.6
        y: -8.15
      68:
        x: 0.0
        y: -7.85
      69:
        x: 1.17
        y: -8.15
      70:
        x: 1.17
        y: -8.6
      71:
        x: 1.17
        y: -8.9
      72:
        x: 2.15
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.9764
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -4.99755
        y: -8.10924
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 0.8132
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9116
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 0.5956
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6469
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 4.2384
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.6798
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      start_delay: 3.3689
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.7019
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      start_delay: 0.7586
