hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_crossing_high_1880881377
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -8.9
      2:
        x: -8.63
        y: -8.6
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -8.63
        y: -8.15
      6:
        x: -8.63
        y: -7.4
      7:
        x: -8.63
        y: -7.1
      8:
        x: -7.65
        y: -5.4
      9:
        x: 10.97
        y: -8.9
      10:
        x: 10.97
        y: -8.6
      11:
        x: 10.97
        y: -8.15
      12:
        x: 10.0
        y: -8.15
      13:
        x: 5.0
        y: -8.15
      14:
        x: 2.6
        y: -8.15
      15:
        x: 0.0
        y: -7.85
      16:
        x: -2.0
        y: -8.18
      17:
        x: -5.0
        y: -8.15
      18:
        x: -3.73
        y: -8.15
      19:
        x: -3.73
        y: -7.4
      20:
        x: -3.73
        y: -7.1
      21:
        x: -2.75
        y: -5.4
      22:
        x: 15.9
        y: 6.4067
      23:
        x: 15.6
        y: 6.4067
      24:
        x: 15.0
        y: 6.4067
      25:
        x: 15.0
        y: 8.0
      26:
        x: 15.0
        y: 3.5
      27:
        x: 15.0
        y: 2.55
      28:
        x: 15.0
        y: 0.0
      29:
        x: 7.0
        y: 0.0
      30:
        x: 7.0
        y: -2.0
      31:
        x: 7.0
        y: -4.0
      32:
        x: 15.0
        y: -4.0
      33:
        x: 15.0
        y: -8.15
      34:
        x: 10.0
        y: -8.15
      35:
        x: 5.0
        y: -8.15
      36:
        x: 2.6
        y: -8.15
      37:
        x: 0.0
        y: -7.85
      38:
        x: -2.0
        y: -8.18
      39:
        x: -5.0
        y: -8.15
      40:
        x: -10.0
        y: -7.85
      41:
        x: -8.63
        y: -8.15
      42:
        x: -8.63
        y: -7.4
      43:
        x: -8.63
        y: -7.1
      44:
        x: -7.65
        y: -5.4
      45:
        x: 1.17
        y: -7.1
      46:
        x: 1.17
        y: -7.4
      47:
        x: 1.17
        y: -8.15
      48:
        x: 0.0
        y: -7.85
      49:
        x: 2.6
        y: -8.15
      50:
        x: 5.0
        y: -8.15
      51:
        x: 6.07
        y: -8.15
      52:
        x: 6.07
        y: -8.6
      53:
        x: 6.07
        y: -8.9
      54:
        x: 7.05
        y: -10.6
      55:
        x: 14.1
        y: 10.71
      56:
        x: 14.4
        y: 10.71
      57:
        x: 15.0
        y: 10.71
      58:
        x: 15.0
        y: 10.65
      59:
        x: 15.0
        y: 9.8
      60:
        x: 15.0
        y: 8.0
      61:
        x: 15.0
        y: 3.5
      62:
        x: 15.0
        y: 2.55
      63:
        x: 15.0
        y: 0.0
      64:
        x: 7.0
        y: 0.0
      65:
        x: 7.0
        y: -2.0
      66:
        x: 7.0
        y: -4.0
      67:
        x: 15.0
        y: -4.0
      68:
        x: 15.0
        y: -8.15
      69:
        x: 10.0
        y: -8.15
      70:
        x: 5.0
        y: -8.15
      71:
        x: 2.6
        y: -8.15
      72:
        x: 0.0
        y: -7.85
      73:
        x: -2.0
        y: -8.18
      74:
        x: -5.0
        y: -8.15
      75:
        x: -10.0
        y: -7.85
      76:
        x: -14.0
        y: -8.15
      77:
        x: -13.53
        y: -8.15
      78:
        x: -13.53
        y: -8.6
      79:
        x: -13.53
        y: -8.9
      80:
        x: -12.55
        y: -10.6
      81:
        x: 15.9
        y: 10.8733
      82:
        x: 15.6
        y: 10.8733
      83:
        x: 15.0
        y: 10.8733
      84:
        x: 15.0
        y: 10.65
      85:
        x: 15.0
        y: 9.8
      86:
        x: 15.0
        y: 8.0
      87:
        x: 15.0
        y: 6.4067
      88:
        x: 15.6
        y: 6.4067
      89:
        x: 15.9
        y: 6.4067
      90:
        x: 17.6
        y: 7.3
      91:
        x: 15.9
        y: 1.94
      92:
        x: 15.6
        y: 1.94
      93:
        x: 15.0
        y: 1.94
      94:
        x: 15.0
        y: 2.55
      95:
        x: 15.0
        y: 3.5
      96:
        x: 15.0
        y: 8.0
      97:
        x: 15.0
        y: 9.8
      98:
        x: 15.0
        y: 10.65
      99:
        x: 15.0
        y: 10.71
      100:
        x: 14.4
        y: 10.71
      101:
        x: 14.1
        y: 10.71
      102:
        x: 12.4
        y: 11.65
      103:
        x: -3.73
        y: -8.9
      104:
        x: -3.73
        y: -8.6
      105:
        x: -3.73
        y: -8.15
      106:
        x: -5.0
        y: -8.15
      107:
        x: -10.0
        y: -7.85
      108:
        x: -8.63
        y: -8.15
      109:
        x: -8.63
        y: -8.6
      110:
        x: -8.63
        y: -8.9
      111:
        x: -7.65
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.982
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      start_delay: 3.4014
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.6209
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      start_delay: 3.6235
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7788
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      start_delay: 4.0808
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.8098
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      start_delay: 0.2161
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.5683
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      start_delay: 4.6459
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.814
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      start_delay: 2.0713
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.6159
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 2.8333
        z: 0.0
        h: -2.657777
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      start_delay: 4.8892
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.7265
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      start_delay: 2.7188
