hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_bidirectional_flow_low_1109160041
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 5.0
        y: -8.15
      2:
        x: 10.0
        y: -8.15
      3:
        x: 2.6
        y: -8.15
      4:
        x: 5.0
        y: -8.15
      5:
        x: 10.0
        y: -8.15
      6:
        x: -5.0
        y: -8.15
      7:
        x: -10.0
        y: -7.85
      8:
        x: -14.0
        y: -8.15
      9:
        x: -10.0
        y: -7.85
      10:
        x: -14.0
        y: -8.15
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.9255
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.6
        y: -8.15
        z: 0.0
        h: 0.0
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 1.1248
    event_agent_2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9789
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 0.0
        y: -7.85
        z: 0.0
        h: -0.114877
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      - 5
      start_delay: 0.0015
    event_agent_3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6622
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.0
        y: -8.18
        z: 0.0
        h: 3.131593
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      start_delay: 1.3986
    event_agent_4:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7184
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -5.0
        y: -8.15
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      start_delay: 0.3534
