hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_overtake_robot_high_494498608
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -5.0
        y: -8.15
      2:
        x: -2.0
        y: -8.18
      3:
        x: 0.0
        y: -7.85
      4:
        x: 2.6
        y: -8.15
      5:
        x: 5.0
        y: -8.15
      6:
        x: 10.0
        y: -8.15
      7:
        x: -8.63
        y: -7.1
      8:
        x: -8.63
        y: -7.4
      9:
        x: -8.63
        y: -8.15
      10:
        x: -10.0
        y: -7.85
      11:
        x: -5.0
        y: -8.15
      12:
        x: -2.0
        y: -8.18
      13:
        x: 0.0
        y: -7.85
      14:
        x: 2.6
        y: -8.15
      15:
        x: 5.0
        y: -8.15
      16:
        x: 10.0
        y: -8.15
      17:
        x: 10.97
        y: -8.15
      18:
        x: 10.97
        y: -8.6
      19:
        x: 10.97
        y: -8.9
      20:
        x: 11.95
        y: -10.6
      21:
        x: -3.73
        y: -7.1
      22:
        x: -3.73
        y: -7.4
      23:
        x: -3.73
        y: -8.15
      24:
        x: -5.0
        y: -8.15
      25:
        x: -2.0
        y: -8.18
      26:
        x: 0.0
        y: -7.85
      27:
        x: 1.17
        y: -8.15
      28:
        x: 1.17
        y: -7.4
      29:
        x: 1.17
        y: -7.1
      30:
        x: 2.15
        y: -5.4
      31:
        x: -13.53
        y: -7.1
      32:
        x: -13.53
        y: -7.4
      33:
        x: -13.53
        y: -8.15
      34:
        x: -14.0
        y: -8.15
      35:
        x: -10.0
        y: -7.85
      36:
        x: -5.0
        y: -8.15
      37:
        x: -2.0
        y: -8.18
      38:
        x: 0.0
        y: -7.85
      39:
        x: 2.6
        y: -8.15
      40:
        x: 5.0
        y: -8.15
      41:
        x: 10.0
        y: -8.15
      42:
        x: 15.0
        y: -8.15
      43:
        x: 15.0
        y: -4.0
      44:
        x: 7.0
        y: -4.0
      45:
        x: 7.0
        y: -2.0
      46:
        x: 7.0
        y: 0.0
      47:
        x: 15.0
        y: 0.0
      48:
        x: 15.0
        y: 2.55
      49:
        x: 15.0
        y: 1.94
      50:
        x: 15.6
        y: 1.94
      51:
        x: 15.9
        y: 1.94
      52:
        x: 17.6
        y: 2.8333
      53:
        x: 6.07
        y: -8.9
      54:
        x: 6.07
        y: -8.6
      55:
        x: 6.07
        y: -8.15
      56:
        x: 5.0
        y: -8.15
      57:
        x: 10.0
        y: -8.15
      58:
        x: 15.0
        y: -8.15
      59:
        x: 15.0
        y: -4.0
      60:
        x: 7.0
        y: -4.0
      61:
        x: 7.0
        y: -2.0
      62:
        x: 7.0
        y: 0.0
      63:
        x: 15.0
        y: 0.0
      64:
        x: 15.0
        y: 2.55
      65:
        x: 15.0
        y: 3.5
      66:
        x: 15.0
        y: 8.0
      67:
        x: 15.0
        y: 9.8
      68:
        x: 15.0
        y: 10.65
      69:
        x: 15.0
        y: 10.8733
      70:
        x: 15.6
        y: 10.8733
      71:
        x: 15.9
        y: 10.8733
      72:
        x: 17.6
        y: 11.7667
      73:
        x: 15.9
        y: 10.8733
      74:
        x: 15.6
        y: 10.8733
      75:
        x: 15.0
        y: 10.8733
      76:
        x: 15.0
        y: 10.65
      77:
        x: 15.0
        y: 10.71
      78:
        x: 14.4
        y: 10.71
      79:
        x: 14.1
        y: 10.71
      80:
        x: 12.4
        y: 11.65
      81:
        x: 10.97
        y: -8.9
      82:
        x: 10.97
        y: -8.6
      83:
        x: 10.97
        y: -8.15
      84:
        x: 10.0
        y: -8.15
      85:
        x: 5.0
        y: -8.15
      86:
        x: 2.6
        y: -8.15
      87:
        x: 0.0
        y: -7.85
      88:
        x: -2.0
        y: -8.18
      89:
        x: -5.0
        y: -8.15
      90:
        x: -10.0
        y: -7.85
      91:
        x: -14.0
        y: -8.15
      92:
        x: -13.53
        y: -8.15
      93:
        x: -13.53
        y: -8.6
      94:
        x: -13.53
        y: -8.9
      95:
        x: -12.55
        y: -10.6
      96:
        x: 1.17
        y: -8.9
      97:
        x: 1.17
        y: -8.6
      98:
        x: 1.17
        y: -8.15
      99:
        x: 0.0
        y: -7.85
      100:
        x: 2.6
        y: -8.15
      101:
        x: 5.0
        y: -8.15
      102:
        x: 10.0
        y: -8.15
      103:
        x: 15.0
        y: -8.15
      104:
        x: 15.0
        y: -4.0
      105:
        x: 7.0
        y: -4.0
      106:
        x: 7.0
        y: -2.0
      107:
        x: 7.0
        y: 0.0
      108:
        x: 15.0
        y: 0.0
      109:
        x: 15.0
        y: 2.55
      110:
        x: 15.0
        y: 3.5
      111:
        x: 15.0
        y: 8.0
      112:
        x: 15.0
        y: 9.8
      113:
        x: 15.0
        y: 10.65
      114:
        x: 15.0
        y: 10.8733
      115:
        x: 15.6
        y: 10.8733
      116:
        x: 15.9
        y: 10.8733
      117:
        x: 17.6
        y: 11.7667
      118:
        x: 14.1
        y: 10.71
      119:
        x: 14.4
        y: 10.71
      120:
        x: 15.0
        y: 10.71
      121:
        x: 15.0
        y: 10.65
      122:
        x: 15.0
        y: 9.8
      123:
        x: 15.0
        y: 8.0
      124:
        x: 15.0
        y: 3.5
      125:
        x: 15.0
        y: 2.55
      126:
        x: 15.0
        y: 0.0
      127:
        x: 7.0
        y: 0.0
      128:
        x: 7.0
        y: -2.0
      129:
        x: 7.0
        y: -4.0
      130:
        x: 15.0
        y: -4.0
      131:
        x: 15.0
        y: -8.15
      132:
        x: 10.0
        y: -8.15
      133:
        x: 5.0
        y: -8.15
      134:
        x: 2.6
        y: -8.15
      135:
        x: 0.0
        y: -7.85
      136:
        x: -2.0
        y: -8.18
      137:
        x: -5.0
        y: -8.15
      138:
        x: -3.73
        y: -8.15
      139:
        x: -3.73
        y: -8.6
      140:
        x: -3.73
        y: -8.9
      141:
        x: -2.75
        y: -10.6
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.8699
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -10.00047
        y: -7.85787
        z: 0.0
        h: -0.059928
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      start_delay: 0.028
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.9581
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      start_delay: 1.2719
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6249
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      start_delay: 3.8097
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.7182
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      start_delay: 2.9163
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.8645
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      - 72
      start_delay: 2.4066
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.8359
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      start_delay: 1.9147
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8821
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      start_delay: 4.2456
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.6927
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 96
      - 97
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      start_delay: 3.9646
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.6365
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      start_delay: 4.5527
