hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_robot_overtake_medium_1581715184
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 15.0
        y: 8.0
      2:
        x: 15.0
        y: 3.5
      3:
        x: 15.0
        y: 2.55
      4:
        x: 14.1
        y: 6.01
      5:
        x: 14.4
        y: 6.01
      6:
        x: 15.0
        y: 6.01
      7:
        x: 15.0
        y: 8.0
      8:
        x: 15.0
        y: 6.4067
      9:
        x: 15.6
        y: 6.4067
      10:
        x: 15.9
        y: 6.4067
      11:
        x: 17.6
        y: 7.3
      12:
        x: -13.53
        y: -8.9
      13:
        x: -13.53
        y: -8.6
      14:
        x: -13.53
        y: -8.15
      15:
        x: -14.0
        y: -8.15
      16:
        x: -10.0
        y: -7.85
      17:
        x: -5.0
        y: -8.15
      18:
        x: -2.0
        y: -8.18
      19:
        x: 0.0
        y: -7.85
      20:
        x: 2.6
        y: -8.15
      21:
        x: 5.0
        y: -8.15
      22:
        x: 10.0
        y: -8.15
      23:
        x: 15.0
        y: -8.15
      24:
        x: 15.0
        y: -4.0
      25:
        x: 7.0
        y: -4.0
      26:
        x: 7.0
        y: -2.0
      27:
        x: 7.0
        y: 0.0
      28:
        x: 15.0
        y: 0.0
      29:
        x: 15.0
        y: 2.55
      30:
        x: 15.0
        y: 3.5
      31:
        x: 15.0
        y: 8.0
      32:
        x: 15.0
        y: 9.8
      33:
        x: 15.0
        y: 10.65
      34:
        x: 15.0
        y: 10.71
      35:
        x: 14.4
        y: 10.71
      36:
        x: 14.1
        y: 10.71
      37:
        x: 12.4
        y: 11.65
      38:
        x: -8.63
        y: -8.9
      39:
        x: -8.63
        y: -8.6
      40:
        x: -8.63
        y: -8.15
      41:
        x: -10.0
        y: -7.85
      42:
        x: -5.0
        y: -8.15
      43:
        x: -2.0
        y: -8.18
      44:
        x: 0.0
        y: -7.85
      45:
        x: 2.6
        y: -8.15
      46:
        x: 5.0
        y: -8.15
      47:
        x: 10.0
        y: -8.15
      48:
        x: 15.0
        y: -8.15
      49:
        x: 15.0
        y: -4.0
      50:
        x: 7.0
        y: -4.0
      51:
        x: 7.0
        y: -2.0
      52:
        x: 7.0
        y: 0.0
      53:
        x: 15.0
        y: 0.0
      54:
        x: 15.0
        y: 2.55
      55:
        x: 15.0
        y: 3.5
      56:
        x: 15.0
        y: 8.0
      57:
        x: 15.0
        y: 9.8
      58:
        x: 15.0
        y: 10.65
      59:
        x: 15.0
        y: 10.8733
      60:
        x: 15.6
        y: 10.8733
      61:
        x: 15.9
        y: 10.8733
      62:
        x: 17.6
        y: 11.7667
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.3159
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 14.97775
        y: 9.8
        z: 0.0
        h: -1.570796
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      start_delay: 0.263
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.8166
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      start_delay: 3.5133
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.5583
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      start_delay: 2.0275
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9572
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      start_delay: 3.5625
