hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_class_change_burst_medium_519315847
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: 6.07
        y: -8.9
      2:
        x: 6.07
        y: -8.6
      3:
        x: 6.07
        y: -8.15
      4:
        x: 5.0
        y: -8.15
      5:
        x: 2.6
        y: -8.15
      6:
        x: 0.0
        y: -7.85
      7:
        x: -2.0
        y: -8.18
      8:
        x: -5.0
        y: -8.15
      9:
        x: -10.0
        y: -7.85
      10:
        x: -14.0
        y: -8.15
      11:
        x: 1.17
        y: -7.1
      12:
        x: 1.17
        y: -7.4
      13:
        x: 1.17
        y: -8.15
      14:
        x: 0.0
        y: -7.85
      15:
        x: -2.0
        y: -8.18
      16:
        x: -5.0
        y: -8.15
      17:
        x: -10.0
        y: -7.85
      18:
        x: -14.0
        y: -8.15
      19:
        x: -3.73
        y: -7.1
      20:
        x: -3.73
        y: -7.4
      21:
        x: -3.73
        y: -8.15
      22:
        x: -5.0
        y: -8.15
      23:
        x: -2.0
        y: -8.18
      24:
        x: 0.0
        y: -7.85
      25:
        x: 2.6
        y: -8.15
      26:
        x: 5.0
        y: -8.15
      27:
        x: 10.0
        y: -8.15
      28:
        x: -8.63
        y: -8.9
      29:
        x: -8.63
        y: -8.6
      30:
        x: -8.63
        y: -8.15
      31:
        x: -10.0
        y: -7.85
      32:
        x: -5.0
        y: -8.15
      33:
        x: -2.0
        y: -8.18
      34:
        x: 0.0
        y: -7.85
      35:
        x: 2.6
        y: -8.15
      36:
        x: 5.0
        y: -8.15
      37:
        x: 10.0
        y: -8.15
      38:
        x: -8.63
        y: -7.1
      39:
        x: -8.63
        y: -7.4
      40:
        x: -8.63
        y: -8.15
      41:
        x: -10.0
        y: -7.85
      42:
        x: -5.0
        y: -8.15
      43:
        x: -2.0
        y: -8.18
      44:
        x: 0.0
        y: -7.85
      45:
        x: 2.6
        y: -8.15
      46:
        x: 5.0
        y: -8.15
      47:
        x: 10.0
        y: -8.15
      48:
        x: -3.73
        y: -8.9
      49:
        x: -3.73
        y: -8.6
      50:
        x: -3.73
        y: -8.15
      51:
        x: -5.0
        y: -8.15
      52:
        x: -2.0
        y: -8.18
      53:
        x: 0.0
        y: -7.85
      54:
        x: 2.6
        y: -8.15
      55:
        x: 5.0
        y: -8.15
      56:
        x: 10.0
        y: -8.15
      57:
        x: 15.0
        y: -8.15
      58:
        x: 15.0
        y: -4.0
      59:
        x: 7.0
        y: -4.0
      60:
        x: 7.0
        y: -2.0
      61:
        x: 7.0
        y: 0.0
      62:
        x: 15.0
        y: 0.0
      63:
        x: 15.0
        y: 2.55
      64:
        x: 15.0
        y: 3.5
      65:
        x: 15.0
        y: 8.0
      66:
        x: 15.0
        y: 9.8
      67:
        x: 15.0
        y: 10.65
      68:
        x: 15.0
        y: 10.8733
      69:
        x: 15.6
        y: 10.8733
      70:
        x: 15.9
        y: 10.8733
      71:
        x: 17.6
        y: 11.7667
      72:
        x: 10.97
        y: -8.9
      73:
        x: 10.97
        y: -8.6
      74:
        x: 10.97
        y: -8.15
      75:
        x: 10.0
        y: -8.15
      76:
        x: 15.0
        y: -8.15
      77:
        x: 15.0
        y: -4.0
      78:
        x: 7.0
        y: -4.0
      79:
        x: 7.0
        y: -2.0
      80:
        x: 7.0
        y: 0.0
      81:
        x: 15.0
        y: 0.0
      82:
        x: 15.0
        y: 2.55
      83:
        x: 15.0
        y: 1.94
      84:
        x: 15.6
        y: 1.94
      85:
        x: 15.9
        y: 1.94
      86:
        x: 17.6
        y: 2.8333
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    - event_agent_5
    - background_agent_1
    - background_agent_2
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.7983
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      start_delay: 0.8306
    event_agent_2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.5673
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      start_delay: 4.3952
    event_agent_3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.7454
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Impassive
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      start_delay: 6.3863
    event_agent_4:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.9446
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Scared
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      start_delay: 4.3613
    event_agent_5:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.8625
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Curious
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      start_delay: 4.7236
    background_agent_1:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.8748
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -2.75
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      - 69
      - 70
      - 71
      start_delay: 3.3928
    background_agent_2:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.6813
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Threatening
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 72
      - 73
      - 74
      - 75
      - 76
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      start_delay: 2.521
