hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_door_bottleneck_high_1333389798
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -8.63
        y: -7.1
      2:
        x: -8.63
        y: -7.4
      3:
        x: -8.63
        y: -8.15
      4:
        x: -10.0
        y: -7.85
      5:
        x: -5.0
        y: -8.15
      6:
        x: 15.9
        y: 6.4067
      7:
        x: 15.6
        y: 6.4067
      8:
        x: 15.0
        y: 6.4067
      9:
        x: 15.0
        y: 8.0
      10:
        x: 15.0
        y: 3.5
      11:
        x: 15.0
        y: 2.55
      12:
        x: 15.0
        y: 0.0
      13:
        x: 7.0
        y: 0.0
      14:
        x: 7.0
        y: -2.0
      15:
        x: 7.0
        y: -4.0
      16:
        x: 15.0
        y: -4.0
      17:
        x: 15.0
        y: -8.15
      18:
        x: 10.0
        y: -8.15
      19:
        x: 5.0
        y: -8.15
      20:
        x: 2.6
        y: -8.15
      21:
        x: 0.0
        y: -7.85
      22:
        x: -2.0
        y: -8.18
      23:
        x: -5.0
        y: -8.15
      24:
        x: -3.73
        y: -8.15
      25:
        x: -3.73
        y: -8.6
      26:
        x: -3.73
        y: -8.9
      27:
        x: -2.75
        y: -10.6
      28:
        x: 10.97
        y: -8.9
      29:
        x: 10.97
        y: -8.6
      30:
        x: 10.97
        y: -8.15
      31:
        x: 10.0
        y: -8.15
      32:
        x: 15.0
        y: -8.15
      33:
        x: 15.0
        y: -4.0
      34:
        x: 7.0
        y: -4.0
      35:
        x: 7.0
        y: -2.0
      36:
        x: 7.0
        y: 0.0
      37:
        x: 15.0
        y: 0.0
      38:
        x: 15.0
        y: 2.55
      39:
        x: 15.0
        y: 1.94
      40:
        x: 15.6
        y: 1.94
      41:
        x: 15.9
        y: 1.94
      42:
        x: 17.6
        y: 2.8333
      43:
        x: -13.53
        y: -7.1
      44:
        x: -13.53
        y: -7.4
      45:
        x: -13.53
        y: -8.15
      46:
        x: -14.0
        y: -8.15
      47:
        x: -10.0
        y: -7.85
      48:
        x: -5.0
        y: -8.15
      49:
        x: -2.0
        y: -8.18
      50:
        x: 0.0
        y: -7.85
      51:
        x: 2.6
        y: -8.15
      52:
        x: 5.0
        y: -8.15
      53:
        x: 10.0
        y: -8.15
      54:
        x: 15.0
        y: -8.15
      55:
        x: 15.0
        y: -4.0
      56:
        x: 7.0
        y: -4.0
      57:
        x: 7.0
        y: -2.0
      58:
        x: 7.0
        y: 0.0
      59:
        x: 15.0
        y: 0.0
      60:
        x: 15.0
        y: 2.55
      61:
        x: 15.0
        y: 3.5
      62:
        x: 15.0
        y: 8.0
      63:
        x: 15.0
        y: 9.8
      64:
        x: 15.0
        y: 10.65
      65:
        x: 15.0
        y: 10.8733
      66:
        x: 15.6
        y: 10.8733
      67:
        x: 15.9
        y: 10.8733
      68:
        x: 17.6
        y: 11.7667
      69:
        x: 14.1
        y: 6.01
      70:
        x: 14.4
        y: 6.01
      71:
        x: 15.0
        y: 6.01
      72:
        x: 15.0
        y: 8.0
      73:
        x: 15.0
        y: 6.4067
      74:
        x: 15.6
        y: 6.4067
      75:
        x: 15.9
        y: 6.4067
      76:
        x: 17.6
        y: 7.3
      77:
        x: -8.63
        y: -8.9
      78:
        x: -8.63
        y: -8.6
      79:
        x: -8.63
        y: -8.15
      80:
        x: -10.0
        y: -7.85
      81:
        x: -5.0
        y: -8.15
      82:
        x: -2.0
        y: -8.18
      83:
        x: 0.0
        y: -7.85
      84:
        x: 2.6
        y: -8.15
      85:
        x: 5.0
        y: -8.15
      86:
        x: 10.0
        y: -8.15
      87:
        x: 15.0
        y: -8.15
      88:
        x: 15.0
        y: -4.0
      89:
        x: 7.0
        y: -4.0
      90:
        x: 7.0
        y: -2.0
      91:
        x: 7.0
        y: 0.0
      92:
        x: 15.0
        y: 0.0
      93:
        x: 15.0
        y: 2.55
      94:
        x: 15.0
        y: 1.94
      95:
        x: 15.6
        y: 1.94
      96:
        x: 15.9
        y: 1.94
      97:
        x: 17.6
        y: 2.8333
      98:
        x: 6.07
        y: -8.9
      99:
        x: 6.07
        y: -8.6
      100:
        x: 6.07
        y: -8.15
      101:
        x: 5.0
        y: -8.15
      102:
        x: 10.0
        y: -8.15
      103:
        x: 15.0
        y: -8.15
      104:
        x: 15.0
        y: -4.0
      105:
        x: 7.0
        y: -4.0
      106:
        x: 7.0
        y: -2.0
      107:
        x: 7.0
        y: 0.0
      108:
        x: 15.0
        y: 0.0
      109:
        x: 15.0
        y: 2.55
      110:
        x: 15.0
        y: 3.5
      111:
        x: 15.0
        y: 8.0
      112:
        x: 15.0
        y: 9.8
      113:
        x: 15.0
        y: 10.65
      114:
        x: 15.0
        y: 10.71
      115:
        x: 14.4
        y: 10.71
      116:
        x: 14.1
        y: 10.71
      117:
        x: 12.4
        y: 11.65
      118:
        x: 15.9
        y: 10.8733
      119:
        x: 15.6
        y: 10.8733
      120:
        x: 15.0
        y: 10.8733
      121:
        x: 15.0
        y: 10.65
      122:
        x: 15.0
        y: 9.8
      123:
        x: 15.0
        y: 8.0
      124:
        x: 15.0
        y: 3.5
      125:
        x: 15.0
        y: 2.55
      126:
        x: 15.0
        y: 0.0
      127:
        x: 7.0
        y: 0.0
      128:
        x: 7.0
        y: -2.0
      129:
        x: 7.0
        y: -4.0
      130:
        x: 15.0
        y: -4.0
      131:
        x: 15.0
        y: -8.15
      132:
        x: 10.0
        y: -8.15
      133:
        x: 5.0
        y: -8.15
      134:
        x: 2.6
        y: -8.15
      135:
        x: 0.0
        y: -7.85
      136:
        x: -2.0
        y: -8.18
      137:
        x: -5.0
        y: -8.15
      138:
        x: -10.0
        y: -7.85
      139:
        x: -14.0
        y: -8.15
      140:
        x: -13.53
        y: -8.15
      141:
        x: -13.53
        y: -8.6
      142:
        x: -13.53
        y: -8.9
      143:
        x: -12.55
        y: -10.6
      144:
        x: 14.1
        y: 10.71
      145:
        x: 14.4
        y: 10.71
      146:
        x: 15.0
        y: 10.71
      147:
        x: 15.0
        y: 10.65
      148:
        x: 15.0
        y: 9.8
      149:
        x: 15.0
        y: 8.0
      150:
        x: 15.0
        y: 6.01
      151:
        x: 14.4
        y: 6.01
      152:
        x: 14.1
        y: 6.01
      153:
        x: 12.4
        y: 6.95
      154:
        x: 1.17
        y: -8.9
      155:
        x: 1.17
        y: -8.6
      156:
        x: 1.17
        y: -8.15
      157:
        x: 0.0
        y: -7.85
      158:
        x: -2.0
        y: -8.18
      159:
        x: -5.0
        y: -8.15
      160:
        x: -10.0
        y: -7.85
      161:
        x: -8.63
        y: -8.15
      162:
        x: -8.63
        y: -7.4
      163:
        x: -8.63
        y: -7.1
      164:
        x: -7.65
        y: -5.4
      165:
        x: 1.17
        y: -7.1
      166:
        x: 1.17
        y: -7.4
      167:
        x: 1.17
        y: -8.15
      168:
        x: 0.0
        y: -7.85
      169:
        x: -2.0
        y: -8.18
      170:
        x: -5.0
        y: -8.15
      171:
        x: -10.0
        y: -7.85
      172:
        x: -14.0
        y: -8.15
      173:
        x: -13.53
        y: -8.15
      174:
        x: -13.53
        y: -7.4
      175:
        x: -13.53
        y: -7.1
      176:
        x: -12.55
        y: -5.4
    agents:
    - event_agent_1
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    - background_agent_5
    - background_agent_6
    - background_agent_7
    - background_agent_8
    - background_agent_9
    - background_agent_10
    event_agent_1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.5932
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      - 3
      - 4
      - 5
      start_delay: 7.5792
    background_agent_1:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.7038
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      start_delay: 2.3135
    background_agent_2:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.6687
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 11.95
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      start_delay: 3.335
    background_agent_3:
      id: 4
      group_id: -1
      skin: 3
      max_vel: 0.8079
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      start_delay: 0.0965
    background_agent_4:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.9952
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 6.95
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 69
      - 70
      - 71
      - 72
      - 73
      - 74
      - 75
      - 76
      start_delay: 1.0987
    background_agent_5:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.9207
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 77
      - 78
      - 79
      - 80
      - 81
      - 82
      - 83
      - 84
      - 85
      - 86
      - 87
      - 88
      - 89
      - 90
      - 91
      - 92
      - 93
      - 94
      - 95
      - 96
      - 97
      start_delay: 4.7179
    background_agent_6:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.7838
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 98
      - 99
      - 100
      - 101
      - 102
      - 103
      - 104
      - 105
      - 106
      - 107
      - 108
      - 109
      - 110
      - 111
      - 112
      - 113
      - 114
      - 115
      - 116
      - 117
      start_delay: 2.3949
    background_agent_7:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.7791
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 11.7667
        z: 0.0
        h: -2.657731
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 118
      - 119
      - 120
      - 121
      - 122
      - 123
      - 124
      - 125
      - 126
      - 127
      - 128
      - 129
      - 130
      - 131
      - 132
      - 133
      - 134
      - 135
      - 136
      - 137
      - 138
      - 139
      - 140
      - 141
      - 142
      - 143
      start_delay: 0.3866
    background_agent_8:
      id: 9
      group_id: -1
      skin: 0
      max_vel: 0.9859
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 12.4
        y: 11.65
        z: 0.0
        h: -0.505099
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 144
      - 145
      - 146
      - 147
      - 148
      - 149
      - 150
      - 151
      - 152
      - 153
      start_delay: 2.5645
    background_agent_9:
      id: 10
      group_id: -1
      skin: 1
      max_vel: 0.7345
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 154
      - 155
      - 156
      - 157
      - 158
      - 159
      - 160
      - 161
      - 162
      - 163
      - 164
      start_delay: 4.0144
    background_agent_10:
      id: 11
      group_id: -1
      skin: 2
      max_vel: 0.6009
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 2.15
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 165
      - 166
      - 167
      - 168
      - 169
      - 170
      - 171
      - 172
      - 173
      - 174
      - 175
      - 176
      start_delay: 0.3987
