hunav_loader:
  ros__parameters:
    yaml_base_name: scenario_opposing_group_high_1715371129
    simulator: Gazebo Fortress
    map: school_arena
    publish_people: true
    global_goals:
      1:
        x: -10.0
        y: -7.85
      2:
        x: -14.0
        y: -8.15
      3:
        x: -10.0
        y: -7.85
      4:
        x: -14.0
        y: -8.15
      5:
        x: -10.0
        y: -7.85
      6:
        x: -14.0
        y: -8.15
      7:
        x: -10.0
        y: -7.85
      8:
        x: -14.0
        y: -8.15
      9:
        x: 6.07
        y: -8.9
      10:
        x: 6.07
        y: -8.6
      11:
        x: 6.07
        y: -8.15
      12:
        x: 5.0
        y: -8.15
      13:
        x: 10.0
        y: -8.15
      14:
        x: 15.0
        y: -8.15
      15:
        x: 15.0
        y: -4.0
      16:
        x: 7.0
        y: -4.0
      17:
        x: 7.0
        y: -2.0
      18:
        x: 7.0
        y: 0.0
      19:
        x: 15.0
        y: 0.0
      20:
        x: 15.0
        y: 2.55
      21:
        x: 15.0
        y: 3.5
      22:
        x: 15.0
        y: 8.0
      23:
        x: 15.0
        y: 6.01
      24:
        x: 14.4
        y: 6.01
      25:
        x: 14.1
        y: 6.01
      26:
        x: 12.4
        y: 6.95
      27:
        x: -8.63
        y: -7.1
      28:
        x: -8.63
        y: -7.4
      29:
        x: -8.63
        y: -8.15
      30:
        x: -10.0
        y: -7.85
      31:
        x: -8.63
        y: -8.15
      32:
        x: -8.63
        y: -8.6
      33:
        x: -8.63
        y: -8.9
      34:
        x: -7.65
        y: -10.6
      35:
        x: 15.9
        y: 6.4067
      36:
        x: 15.6
        y: 6.4067
      37:
        x: 15.0
        y: 6.4067
      38:
        x: 15.0
        y: 8.0
      39:
        x: 15.0
        y: 3.5
      40:
        x: 15.0
        y: 2.55
      41:
        x: 15.0
        y: 0.0
      42:
        x: 7.0
        y: 0.0
      43:
        x: 7.0
        y: -2.0
      44:
        x: 7.0
        y: -4.0
      45:
        x: 15.0
        y: -4.0
      46:
        x: 15.0
        y: -8.15
      47:
        x: 10.0
        y: -8.15
      48:
        x: 5.0
        y: -8.15
      49:
        x: 2.6
        y: -8.15
      50:
        x: 0.0
        y: -7.85
      51:
        x: -2.0
        y: -8.18
      52:
        x: -5.0
        y: -8.15
      53:
        x: -10.0
        y: -7.85
      54:
        x: -14.0
        y: -8.15
      55:
        x: -13.53
        y: -8.15
      56:
        x: -13.53
        y: -8.6
      57:
        x: -13.53
        y: -8.9
      58:
        x: -12.55
        y: -10.6
      59:
        x: -13.53
        y: -8.9
      60:
        x: -13.53
        y: -8.6
      61:
        x: -13.53
        y: -8.15
      62:
        x: -14.0
        y: -8.15
      63:
        x: -10.0
        y: -7.85
      64:
        x: -5.0
        y: -8.15
      65:
        x: -3.73
        y: -8.15
      66:
        x: -3.73
        y: -8.6
      67:
        x: -3.73
        y: -8.9
      68:
        x: -2.75
        y: -10.6
    agents:
    - event_agent_1
    - event_agent_2
    - event_agent_3
    - event_agent_4
    - background_agent_1
    - background_agent_2
    - background_agent_3
    - background_agent_4
    event_agent_1:
      id: 1
      group_id: 1
      skin: 0
      max_vel: 0.7308
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -5.00118
        y: -8.16973
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 1
      - 2
      start_delay: 0.4541
    event_agent_2:
      id: 2
      group_id: 1
      skin: 1
      max_vel: 0.7308
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -5.60874
        y: -8.13794
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 3
      - 4
      start_delay: 0.4541
    event_agent_3:
      id: 3
      group_id: 1
      skin: 2
      max_vel: 0.7308
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -6.21313
        y: -8.05314
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 5
      - 6
      start_delay: 0.4541
    event_agent_4:
      id: 4
      group_id: 1
      skin: 3
      max_vel: 0.7308
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -6.82248
        y: -8.05123
        z: 0.0
        h: 3.081664
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 7
      - 8
      start_delay: 0.4541
    background_agent_1:
      id: 5
      group_id: -1
      skin: 0
      max_vel: 0.9935
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 7.05
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      start_delay: 1.3865
    background_agent_2:
      id: 6
      group_id: -1
      skin: 1
      max_vel: 0.9225
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -7.65
        y: -5.4
        z: 0.0
        h: -2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      start_delay: 1.5338
    background_agent_3:
      id: 7
      group_id: -1
      skin: 2
      max_vel: 0.8472
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: 17.6
        y: 7.3
        z: 0.0
        h: -2.657777
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
      - 54
      - 55
      - 56
      - 57
      - 58
      start_delay: 0.7584
    background_agent_4:
      id: 8
      group_id: -1
      skin: 3
      max_vel: 0.9609
      radius: 0.22
      goal_radius: 0.25
      cyclic_goals: false
      init_pose:
        x: -12.55
        y: -10.6
        z: 0.0
        h: 2.093735
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
      - 59
      - 60
      - 61
      - 62
      - 63
      - 64
      - 65
      - 66
      - 67
      - 68
      start_delay: 4.0413
